(window.AMP = window.AMP || []).push({n:"amp-sidebar", f:(function(AMP) {var process={env:{NODE_ENV:"production"}};function g(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var e in b)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,e);d&&Object.defineProperty(a,e,d)}else a[e]=b[e]};(new Date).getTime();self.log=self.log||{user:null,dev:null};function k(a,b){a=a.__AMP_TOP||a;var c=a.services&&a.services[b]&&a.services[b].obj;return c}function p(a){var b=a;if(b.nodeType){var c=(b.ownerDocument||b).defaultView,e=c=c.__AMP_TOP||c,d=c.services;d||(d=c.services={});c=d;(d=c.ampdoc)||(d=c.ampdoc={obj:null,promise:null,resolve:null});d.obj||(d.obj=(void 0)(e),d.resolve&&d.resolve(d.obj));b=d.obj.getAmpDoc(b)}var h=b.isSingleDoc()?b.win:b;return h&&h.services&&h.services.history&&h.services.history.obj};var q,r="Webkit webkit Moz moz ms O o".split(" ");function u(a,b){void 0===b&&(b="none"==a.style.display);a.style.display=b?"":"none"};var v={NODISPLAY:"nodisplay",FIXED:"fixed",FIXED_HEIGHT:"fixed-height",RESPONSIVE:"responsive",CONTAINER:"container",FILL:"fill",FLEX_ITEM:"flex-item"};function x(a){AMP.BaseElement.apply(this,arguments)}g(x,AMP.BaseElement);x.prototype.isLayoutSupported=function(a){return a==v.NOLAYOUT};
x.prototype.buildCallback=function(){var a=this;this.c=this.win.document;this.m=this.c.documentElement;this.h=this.element.getAttribute("side");this.i=this.getViewport();this.b=!1;this.j=k(this.win,"vsync");var b=k(this.win,"platform");this.o=b.isIos()&&b.isSafari();this.f=-1;this.l=!1;if("left"!=this.h&&"right"!=this.h){var c=this.c.body.getAttribute("dir")||this.m.getAttribute("dir")||"ltr";this.h="rtl"==c?"right":"left";this.element.setAttribute("side",this.h)}this.o&&y(this);z(this)?this.g():
this.element.setAttribute("aria-hidden","true");this.m.addEventListener("keydown",function(b){27==b.keyCode&&a.a()});this.registerAction("toggle",this.s.bind(this));this.registerAction("open",this.g.bind(this));this.registerAction("close",this.a.bind(this))};function z(a){return a.element.hasAttribute("open")}x.prototype.activate=function(){this.g()};x.prototype.s=function(){z(this)?this.a():this.g()};
x.prototype.g=function(){var a=this;z(this)||(this.i.disableTouchZoom(),this.j.mutate(function(){u(a.element,!0);a.i.addToFixedLayer(a.element);A(a);a.o&&B(a);a.element.scrollTop=1;a.j.mutate(function(){a.element.setAttribute("open","");a.element.setAttribute("aria-hidden","false");k(a.win,"timer").delay(function(){var b=a.getRealChildren();a.scheduleLayout(b);a.scheduleResume(b)},550)})}),p(this.getAmpDoc()).push(this.a.bind(this)).then(function(b){a.f=b}))};
x.prototype.a=function(){var a=this;z(this)&&(this.i.restoreOriginalTouchZoom(),this.j.mutate(function(){a.b&&u(a.b,!1);a.element.removeAttribute("open");a.element.setAttribute("aria-hidden","true");k(a.win,"timer").delay(function(){z(a)||(a.i.removeFromFixedLayer(a.element),a.j.mutate(function(){u(a.element,!1);a.schedulePause(a.getRealChildren())}))},550)}),-1!=this.f&&(p(this.getAmpDoc()).pop(this.f),this.f=-1))};
function A(a){if(!a.b){var b=a.c.createElement("div");b.classList.add("-amp-sidebar-mask");b.addEventListener("click",function(){a.a()});a.element.parentNode.appendChild(b);b.addEventListener("touchmove",function(a){a.preventDefault()});a.b=b}u(a.b,!0)}
function y(a){a.element.addEventListener("scroll",function(b){z(a)&&(1>a.element.scrollTop?(a.element.scrollTop=1,b.preventDefault()):a.element.scrollHeight==a.element.scrollTop+a.element.offsetHeight&&(--a.element.scrollTop,b.preventDefault()))})}
function B(a){if(!a.l){var b=a.c.createElement("div"),c={height:"10vh",width:"100%","background-color":"transparent"},e;for(e in c){var d=b,h=c[e],l;l=d.style;var m=e;q||(q=Object.create(null));var n=q[m];if(!n){n=m;if(void 0===l[m]){var f;f=m;f=f.charAt(0).toUpperCase()+f.slice(1);a:{for(var t=0;t<r.length;t++){var w=r[t]+f;if(void 0!==l[w]){f=w;break a}}f=""}void 0!==l[f]&&(n=f)}q[m]=n}(l=n)&&(d.style[l]=h)}a.element.appendChild(b);a.l=!0}}AMP.registerElement("amp-sidebar",x,"amp-sidebar{position:fixed!important;top:0;max-height:100vh!important;height:100vh;max-width:80vw!important;background-color:#efefef;min-width:45px!important;overflow-x:hidden!important;overflow-y:auto!important;z-index:9999!important;-webkit-overflow-scrolling:touch;will-change:transform}amp-sidebar[side=left]{left:0!important;-webkit-transform:translateX(-100%)!important;transform:translateX(-100%)!important}amp-sidebar[side=right]{right:0!important;-webkit-transform:translateX(100%)!important;transform:translateX(100%)!important}amp-sidebar[side][open]{-webkit-transform:translateX(0)!important;transform:translateX(0)!important}amp-sidebar[side]{-webkit-transition:-webkit-transform 233ms cubic-bezier(0,0,.21,1);transition:-webkit-transform 233ms cubic-bezier(0,0,.21,1);transition:transform 233ms cubic-bezier(0,0,.21,1);transition:transform 233ms cubic-bezier(0,0,.21,1),-webkit-transform 233ms cubic-bezier(0,0,.21,1)}.-amp-sidebar-mask{position:fixed!important;top:0!important;left:0!important;width:100vw!important;height:100vh!important;opacity:0.2;background-image:none!important;background-color:#000;z-index:9998!important;display:none}\n/*# sourceURL=/extensions/amp-sidebar/0.1/amp-sidebar.css*/");
})});
//# sourceMappingURL=amp-sidebar-0.1.js.map
