(window.AMP = window.AMP || []).push({n:"amp-iframe", f:(function(AMP) {var process={env:{NODE_ENV:"production"}};var g;function h(a,c){function b(){}b.prototype=c.prototype;a.prototype=new b;a.prototype.constructor=a;for(var d in c)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(c,d);e&&Object.defineProperty(a,d,e)}else a[d]=c[d]};(new Date).getTime();var l=self.log=self.log||{user:null,dev:null};function r(){if(l.user)return l.user;throw Error("failed to call initLogConstructor");};function t(a){a=a.__AMP_TOP||a;var c=a.services&&a.services.timer&&a.services.timer.obj;return c};function w(a,c){var b=a.length-c.length;return 0<=b&&a.indexOf(c,b)==b};var x=(self.AMP_CONFIG||{}).thirdPartyFrameHost||"ampproject.net";var y,A;
function B(a){y||(y=self.document.createElement("a"),A=self.UrlCache||(self.UrlCache=Object.create(null)));var c=A[a];if(c)return c;y.href=a;y.protocol||(y.href=y.href);var b={href:y.href,protocol:y.protocol,host:y.host,hostname:y.hostname,port:"0"==y.port?"":y.port,pathname:y.pathname,search:y.search,hash:y.hash,origin:null};"/"!==b.pathname[0]&&(b.pathname="/"+b.pathname);if("http:"==b.protocol&&80==b.port||"https:"==b.protocol&&443==b.port)b.port="",b.host=b.hostname;b.origin=y.origin&&"null"!=
y.origin?y.origin:"data:"!=b.protocol&&b.host?b.protocol+"//"+b.host:b.href;return A[a]=b};function C(a,c){for(var b=[],d=0;d<a.length;d++){var e=a[d];c(e,d,a)||(b.push(e),a.splice(d,1),d--)}};function D(a,c,b){var d=a.listeningFors;!d&&b&&(d=a.listeningFors=Object.create(null));a=d||null;if(!a)return a;var e=a[c];!e&&b&&(e=a[c]=[]);return e||null}function E(a,c,b){var d=B(c.src).origin,e=b?c.getAttribute("data-amp-3p-sentinel"):"amp";a=D(a,e,!0);for(var f,e=0;e<a.length;e++){var p=a[e];if(p.frame===c){f=p;break}}f||(f={frame:c,origin:d,events:Object.create(null)},a.push(f));return f.events}
function F(a){for(var c={sentinel:"unlisten"},b=a.length-1;0<=b;b--){var d=a[b];if(!d.frame.contentWindow){a.splice(b,1);var e=d.events,f;for(f in e)e[f].splice(0,Infinity).forEach(function(a){a(c)})}}}
function H(a){if(!a.listeningFors){var c=function(b){if(b.data){var c=b.data;if("string"===typeof c&&"{"===c.charAt(0))try{c=JSON.parse(c)}catch(P){var e;if(l.dev)e=l.dev;else throw Error("failed to call initLogConstructor");e.warn("Postmessage could not be parsed. Is it in a valid JSON format?",P)}if(c.sentinel){var f;e=c.sentinel;var p=b.origin,m=b.source,n=D(a,e);if(n){for(var z=0;z<n.length;z++){var u=n[z],v=u.frame.contentWindow;if(v)if("amp"===e){if(u.origin===p&&v==m){f=u;break}}else{var k;
if(!(k=m==v))b:{for(k=m;k&&k!=k.parent;k=k.parent)if(k==v){k=!0;break b}k=!1}if(k){f=u;break}}else setTimeout(F,0,n)}f=f?f.events:null}else f=n;var G=f;if(G){var q=G[c.type];if(q)for(q=q.slice(),f=0;f<q.length;f++)(0,q[f])(c,b.source,b.origin)}}}};a.addEventListener("message",c)}}
function I(a,c,b,d,e){function f(c,d,f){if(e||d==a.contentWindow)"unlisten"==c.sentinel?n():b(c,d,f)}var p=a.ownerDocument.defaultView;H(p);d=E(p,a,d);var m=d[c]||(d[c]=[]),n;m.push(f);return n=function(){if(f){var a=m.indexOf(f);-1<a&&m.splice(a,1);b=m=f=null}}}function J(a,c,b,d,e){if(a.contentWindow){d.type=b;d.sentinel=e?a.getAttribute("data-amp-3p-sentinel"):"amp";var f=d;e&&(f="amp-"+JSON.stringify(d));for(a=0;a<c.length;a++)b=c[a],b.win.postMessage(f,b.origin)}}
function K(a,c,b,d){var e=this;this.a=a;this.m=b;this.h=[];this.J=I(this.a,c,function(a,b,c){e.h.some(function(a){return a.win==b})||e.h.push({win:b,origin:c});d(a,b,c)},this.m,this.m)}K.prototype.send=function(a,c){C(this.h,function(a){return!!a.win.parent});J(this.a,this.h,a,c,this.m)};K.prototype.destroy=function(){this.J();this.h.length=0};function L(a,c,b){var d=this;this.g=a;this.H=t(a.win);this.C=this.G=!1;this.f=[];this.i=0;this.I=this.B.bind(this);this.F=new K(c,"send-intersections",b||!1,function(){return M(d)});this.c=null}L.prototype.fire=function(){if(this.G){var a=this.g.element.getIntersectionChangeEntry();0<this.f.length&&this.f[this.f.length-1].time==a.time||(this.f.push(a),this.i||(this.B(),this.i=this.H.delay(this.I,100)))}};
function M(a){a.G=!0;a.g.getVsync().measure(function(){if(a.g.isInViewport())a.onViewportCallback(!0);a.fire()})}L.prototype.onViewportCallback=function(a){if(this.C!=a)if(this.C=a,this.fire(),a){var c=this.fire.bind(this),b=this.g.getViewport().onScroll(c),d=this.g.getViewport().onChanged(c);this.c=function(){b();d()}}else this.c&&(this.c(),this.c=null)};L.prototype.B=function(){this.i=0;this.f.length&&(this.F.send("intersection",{changes:this.f}),this.f.length=0)};
L.prototype.destroy=function(){this.H.cancel(this.i);this.c&&(this.c(),this.c=null);this.F.destroy()};var N={"AMP-FX-FLYING-CARPET":!0,"AMP-LIGHTBOX":!0,"AMP-STICKY-AD":!0};var O=0,Q=0;function R(a){AMP.BaseElement.apply(this,arguments)}h(R,AMP.BaseElement);g=R.prototype;g.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a};
g.assertSource=function(a,c,b){var d=B(a);r().assert("https:"==d.protocol||"data:"==d.protocol||0==d.origin.indexOf("http://iframe.localhost:"),"Invalid <amp-iframe> src. Must start with https://. Found %s",this.element);var e=B(c);r().assert(!(" "+b+" ").match(/\s+allow-same-origin\s+/i)||d.origin!=e.origin&&"data:"!=d.protocol,"Origin of <amp-iframe> must not be equal to container %sif allow-same-origin is set. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.",
this.element);r().assert(!(w(d.hostname,"."+x)||w(d.hostname,".ampproject.org")),"amp-iframe does not allow embedding of frames from ampproject.*: %s",a);return a};
g.assertPosition=function(){var a=this.element.getLayoutBox(),c=Math.min(600,.75*this.getViewport().getSize().height);r().assert(a.top>=c,"<amp-iframe> elements must be positioned outside the first 75% of the viewport or 600px from the top (whichever is smaller): %s  Current position %s. Min: %sPositioning rules don't apply for iframes that use `placeholder`.See https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#iframe-with-placeholder for details.",this.element,
a.top,c)};g.transformSrcDoc=function(a,c){if(a)return r().assert(!(" "+c+" ").match(/\s+allow-same-origin\s+/i),"allow-same-origin is not allowed with the srcdoc attribute %s.",this.element),"data:text/html;charset=utf-8;base64,"+btoa(a)};
g.firstAttachedCallback=function(){this.w=this.element.getAttribute("sandbox");var a=this.element.getAttribute("src")||this.transformSrcDoc(this.element.getAttribute("srcdoc"),this.w);this.iframeSrc=this.assertSource(a,window.location.href,this.w);var c;c=this.element;if("no"!=c.getAttribute("scrolling")){var b=c.ownerDocument.createElement("i-amp-scroll-container");c.appendChild(b);c=b}this.j=c};g.preconnectCallback=function(a){this.iframeSrc&&this.preconnect.url(this.iframeSrc,a)};
g.buildCallback=function(){this.v=this.getPlaceholder();this.s=!!this.v;this.D=this.o=!1;this.a=this.l=this.c=null;(this.u=this.element.hasAttribute("resizable"))&&this.element.setAttribute("scrolling","no");this.b=null;this.element.hasAttribute("frameborder")||this.element.setAttribute("frameborder","0")};
g.onLayoutMeasure=function(){S(this);var a;a:{var c=this.getIntersectionElementLayoutBox();a=c.height;for(var c=c.width,b=0;b<T.length;b++){var d=T[b][0],e=T[b][1];if(!(e>a||d>c)&&20>=a-e&&20>=c-d){a=!0;break a}}a=!1}if(a=this.o=a){a=this.element;c=this.win;b=!1;d=0;do N[a.tagName]?(d++,b=!1):"fixed"==c.getComputedStyle(a).position&&(b=!0),a=a.parentNode;while(a&&"BODY"!=a.tagName);a=!(!b&&1>=d)}this.D=a;this.b&&this.b.fire()};function S(a){a.a&&(a.l=a.getViewport().getLayoutRect(a.a))}
g.getIntersectionElementLayoutBox=function(){if(!this.a)return AMP.BaseElement.prototype.getIntersectionElementLayoutBox.call(this);this.l||S(this);return this.l};
g.layoutCallback=function(){var a=this;r().assert(!this.D,"amp-iframe is not used for displaying fixed ad. Please use amp-sticky-ad and amp-ad instead.");this.s||this.assertPosition();this.u&&r().assert(this.getOverflowElement(),"Overflow element must be defined for resizable frames: %s",this.element);if(!this.iframeSrc)return Promise.resolve();var c=U(this);if(c&&(Q++,1<Q))return console.error("Only 1 analytics/tracking iframe allowed per page. Please use amp-analytics instead or file a GitHub issue for your use case: https://github.com/ampproject/amphtml/issues/new"),
Promise.resolve();var b=this.element.ownerDocument.createElement("iframe");this.a=b;this.applyFillContent(b);b.name="amp_iframe"+O++;this.s&&(b.style.zIndex=-1);this.propagateAttributes(["frameborder","allowfullscreen","allowtransparency","scrolling","referrerpolicy"],b);V(b,this.w);b.src=this.iframeSrc;c||(this.b=new L(this,b));b.onload=function(){b.readyState="complete";a.A();c&&(a.iframeSrc=null,t(a.win).promise(5E3).then(function(){b.parentElement&&b.parentElement.removeChild(b);a.element.setAttribute("amp-removed",
"");a.a=null}))};I(b,"embed-size",function(b){W(a,b.height,b.width)});this.s&&I(b,"embed-ready",this.A.bind(this));this.j.appendChild(b);return this.loadPromise(b).then(function(){a.j!=a.element&&t(a.win).delay(function(){a.deferMutate(function(){a.j.classList.add("amp-active")})},1E3)})};g.unlayoutOnPause=function(){return!0};
g.unlayoutCallback=function(){if(this.a){var a=this.a;a.parentElement&&a.parentElement.removeChild(a);this.v&&this.togglePlaceholder(!0);this.a=null;this.b&&(this.b.destroy(),this.b=null)}return!0};g.viewportCallback=function(a){if(this.b)this.b.onViewportCallback(a)};g.getPriority=function(){return this.o?2:AMP.BaseElement.prototype.getPriority.call(this)};g.A=function(){var a=this;this.v&&this.getVsync().mutate(function(){a.a&&(a.a.style.zIndex=0,a.togglePlaceholder(!1))})};
g.firstLayoutCompleted=function(){};
function W(a,c,b){if(a.u)if(100>c)r().error("amp-iframe","Ignoring embed-size request because the resize height is less than 100px. If you are using amp-iframe to display ads, consider using amp-ad instead.",a.element);else{var d,e;void 0!==c&&(d=Math.max(a.element.offsetHeight-a.a.offsetHeight+c,c));void 0!==b&&(e=Math.max(a.element.offsetWidth-a.a.offsetWidth+b,b));void 0!==d||void 0!==e?a.attemptChangeSize(d,e).then(function(){void 0!==d&&a.element.setAttribute("height",d);void 0!==e&&a.element.setAttribute("width",
e)},function(){}):r().error("amp-iframe","Ignoring embed-size request becauseno width or height value is provided",a.element)}else r().error("amp-iframe","Ignoring embed-size request because this iframe is not resizable",a.element)}function U(a){var c=a.element.getLayoutBox();return 10<c.width&&10<c.height?!1:!0}function V(a,c){var b=c||"";a.setAttribute("sandbox",b)}var T=[[300,250],[320,50],[300,50],[320,100]];AMP.registerElement("amp-iframe",R);
})});
//# sourceMappingURL=amp-iframe-0.1.js.map
