(window.AMP = window.AMP || []).push({n:"amp-form", f:(function(AMP) {var process={env:{NODE_ENV:"production"}};var k;function m(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};(new Date).getTime();function n(a){for(var b=null,c="",d=0;d<arguments.length;d++){var e=arguments[d];e instanceof Error&&!b?b=e:(c&&(c+=" "),c+=e)}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}function p(a){var b=n.apply(null,arguments);setTimeout(function(){throw b;})}var q=self.log=self.log||{user:null,dev:null};function r(){if(q.user)return q.user;throw Error("failed to call initLogConstructor");};function t(a){if(!a)return[];for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return b};function u(a,b){a=a.__AMP_TOP||a;var c=a.services&&a.services[b]&&a.services[b].obj;return c}function v(a,b,c){a=a.__AMP_TOP||a;var d=a.services;d||(d=a.services={});var e=d[b];e||(e=d[b]={obj:null,promise:null,resolve:null});e.obj||(e.obj=(c?c:void 0)(a),e.resolve&&e.resolve(e.obj));return e.obj};function w(a,b){for(var c=a.firstElementChild;c;c=c.nextElementSibling)if(b(c))return c;return null}var y;function z(a){if(null==y)try{a.ownerDocument.querySelector(":scope"),y=!0}catch(b){y=!1}return y?a.querySelector(":scope > [i-amp-rendered]"):w(a,function(a){return a.hasAttribute("i-amp-rendered")})}function A(a,b){for(var c=[],d=a.parentElement;d;d=d.parentElement)b(d)&&c.push(d);return c}function B(a){var b="fieldset",b=b.toUpperCase();return A(a,function(a){return a.tagName==b})};function C(a){var b=".localhost",c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function D(a){var b=E;return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var E=(self.AMP_CONFIG||{}).cdnUrl||"https://cdn.ampproject.org";var F,G;function aa(a,b){var c=[],d;for(d in b){var e=b[d];if(null!=e)if(Array.isArray(e))for(var f=0;f<e.length;f++){var g=e[f];c.push(encodeURIComponent(d)+"="+encodeURIComponent(g))}else c.push(encodeURIComponent(d)+"="+encodeURIComponent(e))}if(b=c.join("&"))a=a.split("#",2),c=a[0].split("?",2),b=c[0]+(c[1]?"?"+c[1]+"&"+b:"?"+b),a=b+=a[1]?"#"+a[1]:"";return a};var H;
function ba(a){var b="amp-form",c=H||(H=Object.create(null)),d;if(b in c)d=c[b];else{d=b;var e=b,f;if(a._experimentCookie)f=a._experimentCookie;else{c:{d:{try{f=a.document.cookie;break d}catch(x){}f=void 0}if(f){f=f.split(";");for(var g=0;g<f.length;g++){var h=f[g].trim(),l=h.indexOf("=");if(-1!=l&&"AMP_EXP"==decodeURIComponent(h.substring(0,l).trim())){f=decodeURIComponent(h.substring(l+1).trim());break c}}}f=null}f=a._experimentCookie=f?f.split(/\s*,\s*/g):[]}a=-1!=f.indexOf(e)?!0:a.AMP_CONFIG&&a.AMP_CONFIG.hasOwnProperty(e)?
Math.random()<a.AMP_CONFIG[e]:!1;d=c[d]=a}return d};function ca(a){return"loading"!=a.readyState&&"uninitialized"!=a.readyState}function da(a,b){ea(a,b)}function ea(a,b){var c=ca,d=c(a);if(d)b(a);else{var e=function(){c(a)&&(d||(d=!0,b(a)),a.removeEventListener("readystatechange",e))};a.addEventListener("readystatechange",e)}};var I,J="Webkit webkit Moz moz ms O o".split(" ");function K(a,b){for(var c in b){var d=a,e=b[c],f;f=d.style;var g=c;I||(I=Object.create(null));var h=I[g];if(!h){h=g;if(void 0===f[g]){var l;l=g;l=l.charAt(0).toUpperCase()+l.slice(1);a:{for(var x=0;x<J.length;x++){var O=J[x]+l;if(void 0!==f[O]){l=O;break a}}l=""}void 0!==f[l]&&(h=l)}I[g]=h}(f=h)&&(d.style[f]=e)}};function fa(a,b){var c,d,e="form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success]{display:block}.-amp-validation-bubble{-webkit-transform:translate(-50%,-100%);transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,.5);max-width:200px;position:absolute;display:none;box-sizing:border-box;padding:10px;border-radius:5px}.-amp-validation-bubble:after{content:' ';position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{display:none;color:red}[visible-when-invalid].visible{display:initial}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/",
f=ga(a,a.head,e,c||!1,d||null);if(L(a,f))b();else var g=setInterval(function(){L(a,f)&&(clearInterval(g),b())},4)}function ga(a,b,c,d,e){a=a.createElement("style");a.textContent=c;var f=null;d?(a.setAttribute("amp-runtime",""),b.runtimeStyleElement=a):"amp-custom"==e?(a.setAttribute("amp-custom",""),f=b.lastChild):(a.setAttribute("amp-extension",e||""),f=b.runtimeStyleElement);c=b;var g=f;g?g.nextSibling?c.insertBefore(a,g.nextSibling):c.appendChild(a):c.insertBefore(a,c.firstChild);return a}
function L(a,b){var c=a.styleSheets;for(a=0;a<c.length;a++){var d=c[a];if(d.ownerNode==b)return!0}return!1};function M(a,b){this.u=b;this.G=u(a,"viewport");this.l=u(a,"vsync");this.s=null;this.o="";this.i=!1;this.c=a.document.createElement("div");this.c.classList.add("-amp-validation-bubble");this.c.__BUBBLE_OBJ=this;a.document.body.appendChild(this.c)}M.prototype.isActiveOn=function(a){return this.i&&a==this.s};M.prototype.hide=function(){this.i&&(this.i=!1,this.s=null,this.o="",this.l.run({measure:void 0,mutate:ha},{bubbleElement:this.c}))};
M.prototype.show=function(a,b){if(!this.isActiveOn(a)||b!=this.o){this.i=!0;this.s=a;this.o=b;var c={message:b,targetElement:a,bubbleElement:this.c,viewport:this.G,id:this.u};this.l.run({measure:ia,mutate:ja},c)}};function ha(a){a.bubbleElement.removeAttribute("aria-alert");a.bubbleElement.removeAttribute("role");for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);K(a.bubbleElement,{display:"none"})}function ia(a){a.targetRect=a.viewport.getLayoutRect(a.targetElement)}
function ja(a){for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);var c=a.bubbleElement.ownerDocument.createElement("div");c.id="bubble-message-"+a.id;c.textContent=a.message;a.bubbleElement.setAttribute("aria-labeledby",c.id);a.bubbleElement.setAttribute("role","alert");a.bubbleElement.setAttribute("aria-live","assertive");a.bubbleElement.appendChild(c);K(a.bubbleElement,{display:"block",top:a.targetRect.top-10+"px",left:a.targetRect.left+a.targetRect.width/2+"px"})};var N,ka=0;function P(a){this.form=a;this.doc=a.ownerDocument}P.prototype.report=function(){};P.prototype.onBlur=function(){};P.prototype.onInput=function(){};function Q(a){P.apply(this,arguments)}m(Q,P);Q.prototype.report=function(){this.form.reportValidity()};function R(a){P.call(this,a);a=this.doc.defaultView;var b="amp-validation-bubble-"+ka++;this.g=new M(a,b)}m(R,P);
R.prototype.report=function(){for(var a=this.form.querySelectorAll("input,select,textarea"),b=0;b<a.length;b++)if(!a[b].checkValidity()){a[b].focus();this.g.show(a[b],a[b].validationMessage);break}};R.prototype.onBlur=function(){this.g.hide()};R.prototype.onInput=function(a){var b=a.target;this.g.isActiveOn(b)&&(b.checkValidity()?(b.removeAttribute("aria-invalid"),this.g.hide()):(b.setAttribute("aria-invalid","true"),this.g.show(b,b.validationMessage)))};
function S(a){P.call(this,a);this.v={};this.h={}}m(S,P);k=S.prototype;k.reportInput=function(a){var b;a:{for(b in a.validity)if(a.validity[b])break a;b=null}var c=b;c&&this.showValidationFor(a,c)};k.hideAllValidations=function(){for(var a in this.h){var b=this.doc.getElementById(a);this.hideValidationFor(b)}};k.getValidationFor=function(a,b){if(!a.id)return null;a="[visible-when-invalid="+b+"]"+("[validation-for="+a.id+"]");void 0===this.v[a]&&(this.v[a]=this.doc.querySelector(a));return this.v[a]};
k.showValidationFor=function(a,b){var c=this.getValidationFor(a,b);c&&(c.textContent.trim()||(c.textContent=a.validationMessage),a.setAttribute("aria-invalid","true"),c.classList.add("visible"),this.h[a.id]=c)};k.hideValidationFor=function(a){var b=this.getVisibleValidationFor(a);b&&(a.removeAttribute("aria-invalid"),b.classList.remove("visible"),delete this.h[a.id])};k.getVisibleValidationFor=function(a){return a.id?this.h[a.id]:null};
k.shouldValidateOnInteraction=function(){throw Error("Not Implemented");};k.onInteraction=function(a){a=a.target;var b=this.shouldValidateOnInteraction(a);this.hideValidationFor(a);b&&!a.checkValidity()&&this.reportInput(a)};k.onBlur=function(a){this.onInteraction(a)};k.onInput=function(a){this.onInteraction(a)};function T(a){S.apply(this,arguments)}m(T,S);
T.prototype.report=function(){this.hideAllValidations();for(var a=this.form.querySelectorAll("input,select,textarea"),b=0;b<a.length;b++)if(!a[b].checkValidity()){this.reportInput(a[b]);a[b].focus();break}};T.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function U(a){S.apply(this,arguments)}m(U,S);
U.prototype.report=function(){this.hideAllValidations();for(var a=null,b=this.form.querySelectorAll("input,select,textarea"),c=0;c<b.length;c++)b[c].checkValidity()||(a=a||b[c],this.reportInput(b[c]));a&&a.focus()};U.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function V(a){S.apply(this,arguments)}m(V,S);V.prototype.shouldValidateOnInteraction=function(){return!0};
function la(a){var b=a.getAttribute("custom-validation-reporting");switch(b){case "as-you-go":return new V(a);case "show-all-on-submit":return new U(a);case "show-first-on-submit":return new T(a)}void 0===N&&(N=!!a.ownerDocument.createElement("form").reportValidity);return N?new Q(a):new R(a)};function ma(a,b){this.u=b;this.m=a.ownerDocument.defaultView;this.a=a;this.l=u(this.m,"vsync");this.F=u(this.m,"templates");this.H=u(this.m,"xhr");a=this.m.document.documentElement;a=a.nodeType?v((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a;this.A=(a=a.isSingleDoc()?a.win:a)&&a.services&&a.services.action&&a.services.action.obj;this.j=(this.a.getAttribute("method")||"GET").toUpperCase();this.D=this.a.getAttribute("target");if(this.b=this.a.getAttribute("action-xhr")){a=this.b;b=this.a;
var c="action-xhr",c=void 0===c?"source":c;r().assert(null!=a,"%s %s must be available",b,c);var d;F||(F=self.document.createElement("a"),G=self.UrlCache||(self.UrlCache=Object.create(null)));d=G[a];if(!d){F.href=a;F.protocol||(F.href=F.href);d={href:F.href,protocol:F.protocol,host:F.host,hostname:F.hostname,port:"0"==F.port?"":F.port,pathname:F.pathname,search:F.search,hash:F.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&
443==d.port)d.port="",d.host=d.hostname;d.origin=F.origin&&"null"!=F.origin?F.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;G[a]=d}r().assert("https:"==d.protocol||/^(\/\/)/.test(a)||"localhost"==d.hostname||C(d.hostname),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,a);r().assert(!D(this.b),"form action-xhr should not be on cdn.ampproject.org: %s",this.a)}this.B=!this.a.hasAttribute("novalidate");
this.a.setAttribute("novalidate","");this.B||this.a.setAttribute("amp-novalidate","");this.a.classList.add("-amp-form");var e=this.a.querySelectorAll("input[type=submit]");r().assert(e&&0<e.length,"form requires at least one <input type=submit>: %s",this.a);this.C=t(e);this.f=null;a=this.a.elements;for(b=0;b<a.length;b++)r().assert(!a[b].name||"__amp_source_origin"!=a[b].name,"Illegal input name, %s found: %s","__amp_source_origin",a[b]);this.w=la(this.a);na(this)}
function na(a){a.a.addEventListener("submit",function(b){return oa(a,b)},!0);a.a.addEventListener("blur",function(b){W(b.target,!0);a.w.onBlur(b)},!0);a.a.addEventListener("input",function(b){W(b.target,!0);a.w.onInput(b)})}
function oa(a,b){if("submitting"==a.f)b.stopImmediatePropagation();else{var c=pa(a.a);if(a.B&&!c)b.stopImmediatePropagation(),a.l.run({measure:void 0,mutate:qa},{validator:a.w});else if(a.b){b.preventDefault();X(a);Y(a,"submitting");var d="GET"==a.j||"HEAD"==a.j,e=a.b;d&&(e=aa(a.b,ra(a)));a.H.fetchJson(e,{body:d?null:new FormData(a.a),method:a.j,credentials:"include",requireAmpResponseSourceOrigin:!0}).then(function(b){a.A.trigger(a.a,"submit-success",null);Y(a,"submit-success");Z(a,b||{})}).catch(function(b){a.A.trigger(a.a,
"submit-error",null);Y(a,"submit-error");Z(a,b.responseJson||{});p("Form submission failed:",b)})}else"_top"==a.D&&"POST"==a.j&&(X(a),Y(a,"submitting"))}}
function ra(a){var b={};a=a.a.elements;for(var c=/^(?:input|select|textarea)$/i,d=/^(?:button|image|file|reset)$/i,e=/^(?:checkbox|radio)$/i,f=0;f<a.length;f++){var g=a[f],h;if(h=g.name){a:if(g.disabled)h=!0;else{h=B(g);for(var l=0;l<h.length;l++)if(h[l].disabled){h=!0;break a}h=!1}h=!h}!h||!c.test(g.tagName)||d.test(g.type)||e.test(g.type)&&!g.checked||(void 0===b[g.name]&&(b[g.name]=[]),b[g.name].push(g.value))}return b}
function Y(a,b){var c=a.f;a.a.classList.remove("amp-form-"+c);a.a.classList.add("amp-form-"+b);a.f=b;a.C.forEach(function(a){"submitting"==b?a.setAttribute("disabled",""):a.removeAttribute("disabled")})}
function Z(a,b){b=void 0===b?{}:b;var c=a.a.querySelector("["+a.f+"]");if(c){var d="rendered-message-"+a.u;c.setAttribute("role","alert");c.setAttribute("aria-labeledby",d);c.setAttribute("aria-live","assertive");a.F.findAndRenderTemplate(c,b).then(function(a){a.id=d;a.setAttribute("i-amp-rendered","");c.appendChild(a)})}}function X(a){if(a=a.a.querySelector("["+a.f+"]")){var b=z(a);b&&(a=b,a.parentElement&&a.parentElement.removeChild(a))}}function qa(a){a.validator.report()}
function pa(a){for(var b=a.querySelectorAll("input,select,textarea,fieldset"),c=0;c<b.length;c++)W(b[c]);return W(a)}
function W(a,b){b=void 0===b?!1:b;var c=!1,d=a.classList.contains("user-valid")?"valid":a.classList.contains("user-invalid")?"invalid":"none",e=a.checkValidity();"valid"!=d&&e?(a.classList.add("user-valid"),a.classList.remove("user-invalid"),c="invalid"==d):"invalid"==d||e||(a.classList.add("user-invalid"),a.classList.remove("user-valid"),c=!0);if(a.validity)for(var f in a.validity)a.classList.toggle(f,a.validity[f]);if(b&&c){f=B(a);for(var g=0;g<f.length;g++)W(f[g]);a.form&&W(a.form)}return e}
function sa(a){da(a.document,function(a){t(a.forms).forEach(function(a,b){new ma(a,"amp-form-"+b)})})}(function(a){return v(a,"amp-form",function(){ba(a)&&fa(a.document,function(){sa(a)});return{}})})(AMP.win);
})});
//# sourceMappingURL=amp-form-0.1.js.map
