(window.AMP = window.AMP || []).push({n:"amp-analytics", f:(function(AMP) {var process={env:{NODE_ENV:"production"}};var l;function aa(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};(new Date).getTime();var n=self.log=self.log||{user:null,dev:null};function q(){if(n.user)return n.user;throw Error("failed to call initLogConstructor");}function ba(){if(n.dev)return n.dev;throw Error("failed to call initLogConstructor");};var ca=Object.prototype.toString;function t(a,b){a=a.__AMP_TOP||a;var c=a.services&&a.services[b]&&a.services[b].obj;return c}function u(a,b,c){a=a.__AMP_TOP||a;return da(a,a,b,c)}function da(a,b,c,d){var e=ea(a),f=e[c];f||(f=e[c]={obj:null,promise:null,resolve:null});f.obj||(f.obj=d?new d(b):(void 0)(b),f.resolve&&f.resolve(f.obj));return f.obj}function fa(a,b){var c=ga(a,b);if(c)return c;a=ea(a);var d,e=new Promise(function(a){d=a});a[b]={obj:null,promise:e,resolve:d};return e}
function ga(a,b){if(a=ea(a)[b]){if(b=a.promise)return b;if(a.obj)return a.promise=Promise.resolve(a.obj)}return null}function ea(a){var b=a.services;b||(b=a.services={});return b};function ha(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function ia(a,b){ha(a.documentElement,function(){return!!a.body},b)}function ja(a){return new Promise(function(b){ia(a,b)})}function ka(a,b){for(var c=a;c;c=c.parentElement)if(b(c))return c;return null}
function la(a,b){if(a.closest)return a.closest(b);b=b.toUpperCase();return ka(a,function(a){return a.tagName==b})}function ma(a){var b=null,c=na,d=b||function(a){return a},e=a.dataset;a=Object.create(null);var f=c?c:/^param(.+)/,g;for(g in e){var k=g.match(f);if(k){var h=k[1][0].toLowerCase()+k[1].substr(1);a[d(h)]=e[g]}}return a};function oa(a,b,c){return pa(a,b,c).then(function(a){return q().assert(a,"Service %s was requested to be provided through %s, but %s is not loaded in the current page. To fix this problem load the JavaScript file for %s in this page.",b,c,c,c)})}function pa(a,b,c){var d=ga(a,b);return d?d:Promise.resolve().then(function(){return a.ampExtendedElements[c]?fa(a,b):ja(a.document).then(function(){return a.ampExtendedElements[c]?fa(a,b):null})})};function qa(a){var b=".localhost",c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function ra(a,b,c){for(var d=c||1,e={},f=0;f<d&&(e.matches=0,a=a.replace(/\${([^}]*)}/g,function(a){return function(c,d){a.matches++;return b(d)}}(e)),e.matches);e={matches:e.matches},f++);return a};var sa=(self.AMP_CONFIG||{}).cdnUrl||"https://cdn.ampproject.org";var v,ta,ua=/[?&]amp_js[^&]*/;
function y(a){v||(v=self.document.createElement("a"),ta=self.UrlCache||(self.UrlCache=Object.create(null)));var b=ta[a];if(b)return b;v.href=a;v.protocol||(v.href=v.href);var c={href:v.href,protocol:v.protocol,host:v.host,hostname:v.hostname,port:"0"==v.port?"":v.port,pathname:v.pathname,search:v.search,hash:v.hash,origin:null};"/"!==c.pathname[0]&&(c.pathname="/"+c.pathname);if("http:"==c.protocol&&80==c.port||"https:"==c.protocol&&443==c.port)c.port="",c.host=c.hostname;c.origin=v.origin&&"null"!=
v.origin?v.origin:"data:"!=c.protocol&&c.host?c.protocol+"//"+c.host:c.href;return ta[a]=c}function va(a,b){var c;if(!b)return a;var d=a.split("#",2),e=d[0].split("?",2),f=e[0]+(e[1]?c?"?"+b+"&"+e[1]:"?"+e[1]+"&"+b:"?"+b);return f+=d[1]?"#"+d[1]:""}
function wa(a){var b=[],c;for(c in a){var d=a[c];if(null!=d)if(Array.isArray(d))for(var e=0;e<d.length;e++){var f=d[e];b.push(encodeURIComponent(c)+"="+encodeURIComponent(f))}else e=d,b.push(encodeURIComponent(c)+"="+encodeURIComponent(e))}return b.join("&")}
function xa(a){var b,c;c=void 0===c?"source":c;q().assert(null!=a,"%s %s must be available",b,c);var d=y(a);q().assert("https:"==d.protocol||/^(\/\/)/.test(a)||"localhost"==d.hostname||qa(d.hostname),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,a)}function ya(a){"string"==typeof a&&(a=y(a));var b=a.pathname.split("/")[1];return a.origin==sa||0==a.origin.indexOf("http://localhost:")&&("c"==b||"v"==b)};function z(a){return t(a,"viewer")};function za(a){for(var b=new Uint8Array(a.length),c=0;c<a.length;c++){var d=a.charCodeAt(c);b[c]=d}return b};function Aa(a,b){var c;a:{try{c=a.document.cookie;break a}catch(k){}c=void 0}var d=c;if(!d)return null;var e=d.split(";");for(a=0;a<e.length;a++){var f=e[a].trim(),g=f.indexOf("=");if(-1!=g&&decodeURIComponent(f.substring(0,g).trim())==b)return decodeURIComponent(f.substring(g+1).trim())}return null}
function Ba(a,b,c,d,e){"ampproject.org"==e&&(c="delete",d=0);b=encodeURIComponent(b)+"="+encodeURIComponent(c)+"; path=/"+(e?"; domain="+e:"")+"; expires="+(new Date(d)).toUTCString();try{a.document.cookie=b}catch(f){}};function Ca(a,b,c){var d,e=d||!1;a.addEventListener(b,c,e);return function(){a&&a.removeEventListener(b,c,e);a=c=null}}function Da(a,b,c){function d(a){c(a);e()}var e;e=function(){a&&a.removeEventListener(b,d,!1);c=d=a=null};a.addEventListener(b,d,!1);return e}
function Ea(a){var b,c;if(a.complete||"complete"==a.readyState)return Promise.resolve(a);var d=new Promise(function(d,f){b="AUDIO"===a.tagName||"VIDEO"===a.tagName?Da(a,"loadstart",d):Da(a,"load",d);c=Da(a,"error",f)}),d=d.then(function(){return a},Fa);return Ga(d,b,c)}function Fa(a){(a=a.target)&&a.src&&(a=a.src);throw q().createError("Failed to load:",a);}function Ga(a,b,c){var d=void 0,e;e=void 0===d?a:t(self,"timer").timeoutPromise(d||0,a);b&&e.then(b,b);c&&e.then(c,c);return e};function A(){this.I=[]}l=A.prototype;l.add=function(a){var b=this;this.I.push(a);return function(){b.remove(a)}};l.remove=function(a){a=this.I.indexOf(a);-1<a&&this.I.splice(a,1)};l.removeAll=function(){this.I.length=0};l.fire=function(a){for(var b=this.I,c=0;c<b.length;c++)(0,b[c])(a)};l.getHandlerCount=function(){return this.I.length};function B(a){return oa(a,"crypto","amp-analytics")};var Ha=this;function Ia(a,b){a=a.split(".");var c=window||Ha;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]?c=c[d]:c=c[d]={}:c[d]=b}
function Ja(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function Ka(a,b){function c(){}c.prototype=b.prototype;a.v=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.u=function(a,c,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[c].apply(a,g)}}function C(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)}function D(a,b){this.b=a|0;this.a=b|0}var La={},E={};
function F(a){return-128<=a&&128>a?C(La,a,function(a){return new D(a|0,0>a?-1:0)}):new D(a|0,0>a?-1:0)}function G(a){return isNaN(a)?H():a<=-Ma?I():a+1>=Ma?Na():0>a?J(G(-a)):new D(a%L|0,a/L|0)}var L=4294967296,Ma=L*L/2;function H(){return C(E,Oa,function(){return F(0)})}function M(){return C(E,Pa,function(){return F(1)})}function Qa(){return C(E,Ra,function(){return F(-1)})}function Na(){return C(E,Sa,function(){return new D(-1,2147483647)})}
function I(){return C(E,Ta,function(){return new D(0,-2147483648)})}function Ua(){return C(E,Va,function(){return F(16777216)})}
D.prototype.toString=function(a){a=a||10;if(2>a||36<a)throw Error("radix out of range: "+a);if(N(this))return"0";if(0>this.a){if(P(this,I())){var b=G(a),c=Q(this,b),b=R(S(c,b),J(this));return c.toString(a)+b.b.toString(a)}return"-"+J(this).toString(a)}for(var c=G(Math.pow(a,6)),b=this,d="";;){var e=Q(b,c),f=(R(b,J(S(e,c))).b>>>0).toString(a),b=e;if(N(b))return f+d;for(;6>f.length;)f="0"+f;d=""+f+d}};function T(a){return 0<=a.b?a.b:L+a.b}function N(a){return 0==a.a&&0==a.b}
function P(a,b){return a.a==b.a&&a.b==b.b}function U(a,b){if(P(a,b))return 0;var c=0>a.a,d=0>b.a;return c&&!d?-1:!c&&d?1:0>R(a,J(b)).a?-1:1}function J(a){return P(a,I())?I():R(new D(~a.b,~a.a),M())}function R(a,b){var c=a.a>>>16,d=a.a&65535,e=a.b>>>16,f=b.a>>>16,g=b.a&65535,k=b.b>>>16;a=0+((a.b&65535)+(b.b&65535));k=0+(a>>>16)+(e+k);e=0+(k>>>16)+(d+g);return new D((k&65535)<<16|a&65535,(0+(e>>>16)+(c+f)&65535)<<16|e&65535)}
function S(a,b){if(N(a)||N(b))return H();if(P(a,I()))return 1==(b.b&1)?I():H();if(P(b,I()))return 1==(a.b&1)?I():H();if(0>a.a)return 0>b.a?S(J(a),J(b)):J(S(J(a),b));if(0>b.a)return J(S(a,J(b)));if(0>U(a,Ua())&&0>U(b,Ua()))return G((a.a*L+T(a))*(b.a*L+T(b)));var c=a.a>>>16,d=a.a&65535,e=a.b>>>16;a=a.b&65535;var f=b.a>>>16,g=b.a&65535,k=b.b>>>16;b=b.b&65535;var h,m,w,r;r=0+a*b;w=0+(r>>>16)+e*b;m=0+(w>>>16);w=(w&65535)+a*k;m=m+(w>>>16)+d*b;h=0+(m>>>16);m=(m&65535)+e*k;h+=m>>>16;m=(m&65535)+a*g;return new D((w&
65535)<<16|r&65535,(h+(m>>>16)+(c*b+d*k+e*g+a*f)&65535)<<16|m&65535)}
function Q(a,b){if(N(b))throw Error("division by zero");if(N(a))return H();if(P(a,I())){if(P(b,M())||P(b,Qa()))return I();if(P(b,I()))return M();var c;c=1;if(0==c)c=a;else{var d=a.a;c=32>c?new D(a.b>>>c|d<<32-c,d>>c):new D(d>>c-32,0<=d?0:-1)}c=Q(c,b);d=1;if(0!=d){var e=c.b;c=32>d?new D(e<<d,c.a<<d|e>>>32-d):new D(0,e<<d-32)}if(P(c,H()))return 0>b.a?M():Qa();a=R(a,J(S(b,c)));return R(c,Q(a,b))}if(P(b,I()))return H();if(0>a.a)return 0>b.a?Q(J(a),J(b)):J(Q(J(a),b));if(0>b.a)return J(Q(a,J(b)));for(d=
H();0<=U(a,b);){c=Math.max(1,Math.floor((a.a*L+T(a))/(b.a*L+T(b))));for(var e=Math.ceil(Math.log(c)/Math.LN2),e=48>=e?1:Math.pow(2,e-48),f=G(c),g=S(f,b);0>g.a||0<U(g,a);)c-=e,f=G(c),g=S(f,b);N(f)&&(f=M());d=R(d,f);a=R(a,J(g))}return d}var Sa=1,Ta=2,Oa=3,Pa=4,Ra=5,Va=6;
function Wa(a,b){this.g=128;this.h=void 0!==Ha.Uint8Array?new Uint8Array(128):Array(128);this.j=this.f=0;this.c=[];this.l=a;this.s=[];this.o=Xa(b);this.i=!1;this.j=this.f=0;a=this.o;b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];a=c}else a=[];this.c=a;this.i=!1}Ka(Wa,function(){this.g=-1});for(var Ya=[],Za=0;127>Za;Za++)Ya[Za]=0;var $a=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)}([128],Ya);
function ab(a,b,c){c=void 0!==c?c:b.length;if(a.i)throw Error("this hasher needs to be reset");var d=a.f;if("string"==typeof b)for(var e=0;e<c;e++){var f=b.charCodeAt(e);if(255<f)throw Error("Characters must be in range [0,255]");a.h[d++]=f;d==a.g&&(bb(a),d=0)}else if(e=Ja(b),"array"==e||"object"==e&&"number"==typeof b.length)for(e=0;e<c;e++){f=b[e];if("number"!=typeof f||0>f||255<f||f!=(f|0))throw Error("message must be a byte array");a.h[d++]=f;d==a.g&&(bb(a),d=0)}else throw Error("message must be string or array");
a.f=d;a.j+=c}
function bb(a){for(var b=a.h,c=a.s,d=0;16>d;d++){var e=8*d;c[d]=new D(b[e+4]<<24|b[e+5]<<16|b[e+6]<<8|b[e+7],b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3])}for(d=16;80>d;d++){var e=c[d-15],b=e.b,e=e.a,f=c[d-2],g=f.b,f=f.a;c[d]=a.m(c[d-16],c[d-7],new D(b>>>1^e<<31^b>>>8^e<<24^b>>>7^e<<25,e>>>1^b<<31^e>>>8^b<<24^e>>>7),new D(g>>>19^f<<13^f>>>29^g<<3^g>>>6^f<<26,f>>>19^g<<13^g>>>29^f<<3^f>>>6))}for(var b=a.c[0],e=a.c[1],g=a.c[2],f=a.c[3],k=a.c[4],h=a.c[5],m=a.c[6],w=a.c[7],d=0;80>d;d++)var r=b.b,p=b.a,r=R(new D(r>>>
28^p<<4^p>>>2^r<<30^p>>>7^r<<25,p>>>28^r<<4^r>>>2^p<<30^r>>>7^p<<25),new D(b.b&e.b|e.b&g.b|b.b&g.b,b.a&e.a|e.a&g.a|b.a&g.a)),p=k.b,x=k.a,O=k.b,K=k.a,p=a.m(w,new D(p>>>14^x<<18^p>>>18^x<<14^x>>>9^p<<23,x>>>14^p<<18^x>>>18^p<<14^p>>>9^x<<23),new D(O&h.b|~O&m.b,K&h.a|~K&m.a),cb[d],c[d]),w=m,m=h,h=k,k=R(f,p),f=g,g=e,e=b,b=R(p,r);a.c[0]=R(a.c[0],b);a.c[1]=R(a.c[1],e);a.c[2]=R(a.c[2],g);a.c[3]=R(a.c[3],f);a.c[4]=R(a.c[4],k);a.c[5]=R(a.c[5],h);a.c[6]=R(a.c[6],m);a.c[7]=R(a.c[7],w)}
Wa.prototype.m=function(a,b,c){for(var d=(a.b^2147483648)+(b.b^2147483648),e=a.a+b.a,f=arguments.length-1;2<=f;--f)d+=arguments[f].b^2147483648,e+=arguments[f].a;arguments.length&1&&(d+=2147483648);e+=arguments.length>>1;e+=Math.floor(d/4294967296);return new D(d,e)};function Xa(a){for(var b=[],c=0;c<a.length;c+=2)b.push(new D(a[c+1],a[c]));return b}
var cb=Xa([1116352408,3609767458,1899447441,602891725,3049323471,3964484399,3921009573,2173295548,961987163,4081628472,1508970993,3053834265,2453635748,2937671579,2870763221,3664609560,3624381080,2734883394,310598401,1164996542,607225278,1323610764,1426881987,3590304994,1925078388,4068182383,2162078206,991336113,2614888103,633803317,3248222580,3479774868,3835390401,2666613458,4022224774,944711139,264347078,2341262773,604807628,2007800933,770255983,1495990901,1249150122,1856431235,1555081692,3175218132,
1996064986,2198950837,2554220882,3999719339,2821834349,766784016,2952996808,2566594879,3210313671,3203337956,3336571891,1034457026,3584528711,2466948901,113926993,3758326383,338241895,168717936,666307205,1188179964,773529912,1546045734,1294757372,1522805485,1396182291,2643833823,1695183700,2343527390,1986661051,1014477480,2177026350,1206759142,2456956037,344077627,2730485921,1290863460,2820302411,3158454273,3259730800,3505952657,3345764771,106217008,3516065817,3606008344,3600352804,1432725776,4094571909,
1467031594,275423344,851169720,430227734,3100823752,506948616,1363258195,659060556,3750685593,883997877,3785050280,958139571,3318307427,1322822218,3812723403,1537002063,2003034995,1747873779,3602036899,1955562222,1575990012,2024104815,1125592928,2227730452,2716904306,2361852424,442776044,2428436474,593698344,2756734187,3733110249,3204031479,2999351573,3329325298,3815920427,3391569614,3928383900,3515267271,566280711,3940187606,3454069534,4118630271,4000239992,116418474,1914138554,174292421,2731055270,
289380356,3203993006,460393269,320620315,685471733,587496836,852142971,1086792851,1017036298,365543100,1126000580,2618297676,1288033470,3409855158,1501505948,4234509866,1607167915,987167468,1816402316,1246189591]);function db(){Wa.call(this,6,eb)}Ka(db,Wa);var eb=[3418070365,3238371032,1654270250,914150663,2438529370,812702999,355462360,4144912697,1731405415,4290775857,2394180231,1750603025,3675008525,1694076839,1203062813,3204075428],fb=null,gb=null;
Ia("ampBase64",function(a){if(!fb){fb={};gb={};for(var b=0;65>b;b++)fb[b]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b),gb[b]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(b)}for(var b=gb,c=[],d=0;d<a.length;d+=3){var e=a[d],f=d+1<a.length,g=f?a[d+1]:0,k=d+2<a.length,h=k?a[d+2]:0,m=e>>2,e=(e&3)<<4|g>>4,g=(g&15)<<2|h>>6,h=h&63;k||(h=64,f||(g=64));c.push(b[m],b[e],b[g],b[h])}return c.join("")});
Ia("ampSha384Digest",function(a){var b=new db;ab(b,a);if(b.i)throw Error("this hasher needs to be reset");var c=8*b.j;112>b.f?ab(b,$a,112-b.f):ab(b,$a,b.g-b.f+112);for(a=127;112<=a;a--)b.h[a]=c&255,c/=256;bb(b);var c=0,d=Array(8*b.l);for(a=0;a<b.l;a++){for(var e=b.c[a],f=e.a,e=e.b,g=24;0<=g;g-=8)d[c++]=f>>g&255;for(g=24;0<=g;g-=8)d[c++]=e>>g&255}b.i=!0;return d});function hb(a,b){var c=0;"active"===a.type&&(c=5);return Math.min(b-a.time,c)}function ib(){this.Y=0;this.F=void 0}ib.prototype.push=function(a){this.F||(this.F=a);this.F.time<a.time&&(this.Y+=hb(this.F,a.time),this.F=a)};ib.prototype.getTotalEngagedTime=function(a){var b=0;void 0!==this.F&&(b=this.Y+hb(this.F,a));return b};var jb=["mousedown","mouseup","mousemove","keydown","keyup"];
function kb(a){this.A=a;this.sa=this.Ca.bind(this);this.ba=this.W.bind(this);this.Da=this.ha.bind(this);this.ra=this.wa.bind(this);this.M=[];this.O=this.N=!1;this.Z=new ib;this.B=z(this.A);this.D=t(this.A,"viewport");this.B.whenFirstVisible().then(this.Ba.bind(this))}l=kb.prototype;l.Ba=function(){this.Aa=Date.now();this.W();for(var a=0;a<jb.length;a++)this.M.push(Ca(this.A.document,jb[a],this.ba));this.M.push(this.B.onVisibilityChanged(this.ra));this.D.onScroll(this.ba)};
function lb(a){var b=Date.now()-a.Aa;return 0<b?b:0}l.Ca=function(){this.O=this.N=!1};l.W=function(){this.N||(this.N=!0,this.O=!1,mb(this,"active"))};l.ha=function(){this.O||(this.O=!0,this.N=!1,mb(this,"inactive"))};function mb(a,b){var c=lb(a),d=Math.floor(c/1E3),e=1E3-c%1E3;setTimeout(a.sa,e);a.Z.push({type:b,time:d})}l.wa=function(){this.B.isVisible()?this.W():this.ha()};l.Ea=function(){for(var a=0;a<this.M.length;a++){var b=this.M[a];"function"===typeof b&&b()}this.M=[]};
l.getTotalEngagedTime=function(){var a=Math.floor(lb(this)/1E3);return this.Z.getTotalEngagedTime(a)};var nb={"default":{transport:{beacon:!0,xhrpost:!0,image:!0},vars:{accessReaderId:"ACCESS_READER_ID",ampdocHost:"AMPDOC_HOST",ampdocUrl:"AMPDOC_URL",ampVersion:"AMP_VERSION",authdata:"AUTHDATA",availableScreenHeight:"AVAILABLE_SCREEN_HEIGHT",availableScreenWidth:"AVAILABLE_SCREEN_WIDTH",browserLanguage:"BROWSER_LANGUAGE",canonicalHost:"CANONICAL_HOST",canonicalPath:"CANONICAL_PATH",canonicalUrl:"CANONICAL_URL",clientId:"CLIENT_ID",contentLoadTime:"CONTENT_LOAD_TIME",documentCharset:"DOCUMENT_CHARSET",
documentReferrer:"DOCUMENT_REFERRER",domainLookupTime:"DOMAIN_LOOKUP_TIME",domInteractiveTime:"DOM_INTERACTIVE_TIME",navRedirectCount:"NAV_REDIRECT_COUNT",navTiming:"NAV_TIMING",navType:"NAV_TYPE",pageDownloadTime:"PAGE_DOWNLOAD_TIME",pageLoadTime:"PAGE_LOAD_TIME",pageViewId:"PAGE_VIEW_ID",queryParam:"QUERY_PARAM",random:"RANDOM",redirectTime:"REDIRECT_TIME",screenColorDepth:"SCREEN_COLOR_DEPTH",screenHeight:"SCREEN_HEIGHT",screenWidth:"SCREEN_WIDTH",scrollHeight:"SCROLL_HEIGHT",scrollLeft:"SCROLL_LEFT",
scrollTop:"SCROLL_TOP",scrollWidth:"SCROLL_WIDTH",serverResponseTime:"SERVER_RESPONSE_TIME",sourceUrl:"SOURCE_URL",sourceHost:"SOURCE_HOST",sourcePath:"SOURCE_PATH",tcpConnectTime:"TCP_CONNECT_TIME",timestamp:"TIMESTAMP",timezone:"TIMEZONE",title:"TITLE",totalEngagedTime:"TOTAL_ENGAGED_TIME",viewer:"VIEWER",viewportHeight:"VIEWPORT_HEIGHT",viewportWidth:"VIEWPORT_WIDTH"}},afsanalytics:{vars:{server:"www",websiteid:"xxxxxxxx",event:"click",clicklabel:"clicked from AMP page"},transport:{beacon:!1,xhrpost:!1,
image:!0},requests:{host:"//${server}.afsanalytics.com",base:"${host}/cgi_bin/",pageview:"${base}connect.cgi?usr=${websiteid}Pauto&js=1&amp=1&title=${title}&url=${canonicalUrl}&refer=${documentReferrer}&resolution=${screenWidth}x${screenHeight}&color=${screenColorDepth}&Tips=${random}",click:"${base}click.cgi?usr=${websiteid}&event=${event}&exit=${clicklabel}"},triggers:{defaultPageview:{on:"visible",request:"pageview"}}},atinternet:{transport:{beacon:!1,xhrpost:!1,image:!0},requests:{base:"https://${log}${domain}/hit.xiti?s=${site}&ts=${timestamp}&r=${screenWidth}x${screenHeight}x${screenColorDepth}&re=${availableScreenWidth}x${availableScreenHeight}",
suffix:"&medium=amp&${extraUrlParams}&ref=${documentReferrer}",pageview:"${base}&p=${title}&s2=${level2}${suffix}",click:"${base}&pclick=${title}&s2click=${level2}&p=${label}&s2=${level2Click}&type=click&click=${type}${suffix}"}},burt:{vars:{trackingKey:"ignore",category:"",subCategory:""},requests:{host:"//${trackingKey}.c.richmetrics.com/",base:"${host}imglog?e=${trackingKey}&pi=${trackingKey}|${pageViewId}|${canonicalPath}|${clientId(burt-amp-user-id)}&ui=${clientId(burt-amp-user-id)}&v=amp&ts=${timestamp}&sn=${requestCount}&",
pageview:"${base}type=page&ca=${category}&sc=${subCategory}&ln=${browserLanguage}&lr=${documentReferrer}&eu=${sourceUrl}&tz=${timezone}&pd=${scrollWidth}x${scrollHeight}&sd=${screenWidth}x${screenHeight}&wd=${availableScreenWidth}x${availableScreenHeight}&ws=${scrollLeft}x${scrollTop}",pageping:"${base}type=pageping"},triggers:{pageview:{on:"visible",request:"pageview"},pageping:{on:"timer",timerSpec:{interval:15,maxTimerLength:1200},request:"pageping"}},transport:{beacon:!1,xhrpost:!1,image:!0}},
chartbeat:{requests:{host:"https://ping.chartbeat.net",basePrefix:"/ping?h=${domain}&p=${canonicalPath}&u=${clientId(_cb)}&d=${canonicalHost}&g=${uid}&g0=${sections}&g1=${authors}&g2=${zone}&g3=${sponsorName}&g4=${contentType}&c=120&x=${scrollTop}&y=${scrollHeight}&j=${decayTime}&R=1&W=0&I=0&E=${totalEngagedTime}&r=${documentReferrer}&t=${pageViewId}${clientId(_cb)}&b=${pageLoadTime}&i=${title}&T=${timestamp}&tz=${timezone}&C=2",baseSuffix:"&_",interval:"${host}${basePrefix}${baseSuffix}",anchorClick:"${host}${basePrefix}${baseSuffix}"},
triggers:{trackInterval:{on:"timer",timerSpec:{interval:15,maxTimerLength:7200},request:"interval",vars:{decayTime:30}},trackAnchorClick:{on:"click",selector:"a",request:"anchorClick",vars:{decayTime:30}}},transport:{beacon:!1,xhrpost:!1,image:!0}},clicky:{vars:{site_id:""},requests:{base:"https://in.getclicky.com/in.php?site_id=${site_id}",baseSuffix:"&mime=${contentType}&x=${random}",pageview:"${base}&res=${screenWidth}x${screenHeight}&lang=${browserLanguage}&secure=1&type=pageview&href=${canonicalPath}&title=${title}${baseSuffix}",
interval:"${base}&type=ping${baseSuffix}"},triggers:{defaultPageview:{on:"visible",request:"pageview"},interval:{on:"timer",timerSpec:{interval:60,maxTimerLength:600},request:"interval"}},transport:{beacon:!1,xhrpost:!1,image:!0}},colanalytics:{requests:{host:"https://ase.clmbtech.com",base:"${host}/message",pageview:"${base}?cid=${id}&val_101=${id}&val_101=${canonicalPath}&ch=${canonicalHost}&uuid=${uid}&au=${authors}&zo=${zone}&sn=${sponsorName}&ct=${contentType}&st=${scrollTop}&sh=${scrollHeight}&dct=${decayTime}&tet=${totalEngagedTime}&dr=${documentReferrer}&plt=${pageLoadTime}&val_108=${title}&val_120=3"},
triggers:{defaultPageview:{on:"visible",request:"pageview"}},transport:{beacon:!1,xhrpost:!1,image:!0}},comscore:{vars:{c2:"1000001"},requests:{host:"https://sb.scorecardresearch.com",base:"${host}/b?",pageview:"${base}c1=2&c2=${c2}&rn=${random}&c8=${title}&c7=${canonicalUrl}&c9=${documentReferrer}&cs_c7amp=${ampdocUrl}"},triggers:{defaultPageview:{on:"visible",request:"pageview"}},transport:{beacon:!1,xhrpost:!1,image:!0}},cxense:{requests:{host:"https://scomcluster.cxense.com",base:"${host}/Repo/rep.gif",
pageview:"${base}?ver=1&typ=pgv&sid=${siteId}&ckp=${clientId(cX_P)}&loc=${sourceUrl}&rnd=${random}&ref=${documentReferrer}&ltm=${timestamp}&wsz=${screenWidth}x${screenHeight}&bln=${browserLanguage}&chs=${documentCharset}&col=${screenColorDepth}&tzo=${timezone}&cp_cx_channel=amp"},triggers:{defaultPageview:{on:"visible",request:"pageview"}},transport:{beacon:!1,xhrpost:!1,image:!0}},googleanalytics:{vars:{eventValue:"0",documentLocation:"SOURCE_URL",clientId:"CLIENT_ID(AMP_ECID_GOOGLE)",dataSource:"AMP"},
requests:{host:"https://www.google-analytics.com",basePrefix:"v=1&_v=a1&ds=${dataSource}&aip=true&_s=${requestCount}&dt=${title}&sr=${screenWidth}x${screenHeight}&_utmht=${timestamp}&jid=&cid=${clientId}&tid=${account}&dl=${documentLocation}&dr=${documentReferrer}&sd=${screenColorDepth}&ul=${browserLanguage}&de=${documentCharset}",baseSuffix:"&a=${pageViewId}&z=${random}",pageview:"${host}/r/collect?${basePrefix}&t=pageview&_r=1${baseSuffix}",event:"${host}/collect?${basePrefix}&t=event&ec=${eventCategory}&ea=${eventAction}&el=${eventLabel}&ev=${eventValue}${baseSuffix}",
social:"${host}/collect?${basePrefix}&t=social&sa=${socialAction}&sn=${socialNetwork}&st=${socialTarget}${baseSuffix}",timing:"${host}/collect?${basePrefix}&t=timing&plt=${pageLoadTime}&dns=${domainLookupTime}&tcp=${tcpConnectTime}&rrt=${redirectTime}&srt=${serverResponseTime}&pdt=${pageDownloadTime}&clt=${contentLoadTime}&dit=${domInteractiveTime}${baseSuffix}"},triggers:{performanceTiming:{on:"visible",request:"timing",sampleSpec:{sampleOn:"${clientId}",threshold:1}}},extraUrlParamsReplaceMap:{dimension:"cd",
metric:"cm"},optout:"_gaUserPrefs.ioo"},krux:{requests:{beaconHost:"https://beacon.krxd.net",timing:"t_navigation_type=0&t_dns=${domainLookupTime}&t_tcp=${tcpConnectTime}&t_http_request=${serverResponseTime}&t_http_response=${pageDownloadTime}&t_content_ready=${contentLoadTime}&t_window_load=${pageLoadTime}&t_redirect=${redirectTime}",common:"source=amp&confid=${confid}&_kpid=${pubid}&_kcp_s=${site}&_kcp_sc=${section}&_kcp_ssc=${subsection}&_kcp_d=${canonicalHost}&_kpref_=${documentReferrer}&_kua_kx_amp_client_id=${clientId(_kuid_)}&_kua_kx_lang=${browserLanguage}&_kua_kx_tech_browser_language=${browserLanguage}&_kua_kx_tz=${timezone}",
pageview:"${beaconHost}/pixel.gif?${common}&${timing}",event:"${beaconHost}/event.gif?${common}&${timing}&pageview=false"},transport:{beacon:!1,xhrpost:!1,image:!0},extraUrlParamsReplaceMap:{"user.":"_kua_","page.":"_kpa_"}},lotame:{requests:{pageview:"https://bcp.crwdcntrl.net/amp?c=${account}&pv=y"},triggers:{"track pageview":{on:"visible",request:"pageview"}},transport:{beacon:!1,xhrpost:!1,image:!0}},mediametrie:{requests:{host:"https://prof.estat.com/m/web",pageview:"${host}/${serial}?c=${level1}&dom=${ampdocUrl}&enc=${documentCharset}&l3=${level3}&l4=${level4}&n=${random}&p=${level2}&r=${documentReferrer}&sch=${screenHeight}&scw=${screenWidth}&tn=amp&v=1&vh=${availableScreenHeight}&vw=${availableScreenWidth}"},
triggers:{trackPageview:{on:"visible",request:"pageview"}},transport:{beacon:!1,xhrpost:!1,image:!0}},mparticle:{vars:{eventType:"Unknown",debug:!1,amp_clientId:"CLIENT_ID(mparticle_amp_id)"},requests:{host:"https://pixels.mparticle.com",endpointPath:"/v1/${apiKey}/Pixel",baseParams:"et=${eventType}&amp_id=${amp_clientId}&attrs_k=${eventAttributes_Keys}&attrs_v=${eventAttributes_Values}&ua_k=${userAttributes_Keys}&ua_v=${userAttributes_Values}&ui_t=${userIdentities_Types}&ui_v=${userIdentities_Values}&flags_k=${customFlags_Keys}&flags_v=${customFlags_Values}&ct=${timestamp}&dbg=${debug}&lc=${location}&av=${appVersion}",
pageview:"${host}${endpointPath}?dt=ScreenView&n=${canonicalPath}&hn=${ampdocUrl}&ttl=${title}&${baseParams}",event:"${host}${endpointPath}?dt=AppEvent&n=${eventName}&${baseParams}"},transport:{beacon:!1,xhrpost:!1,image:!0}},oewadirect:{transport:{beacon:!1,xhrpost:!1,image:!0},requests:{pageview:"https://${s}.oewabox.at/j0=,,,r=${canonicalUrl};+,amp=1+cp=${cp}+ssl=1+hn=${canonicalHost};;;?lt=${pageViewId}&x=${screenWidth}x${screenHeight}x24&c=CLIENT_ID(oewa)"},triggers:{pageview:{on:"visible",request:"pageview"}}},
oewa:{transport:{beacon:!1,xhrpost:!1,image:!0},requests:{pageview:"${url}?s=${s}&amp=1&cp=${cp}&host=${canonicalHost}&path=${canonicalPath}"},triggers:{pageview:{on:"visible",request:"pageview"}}},parsely:{requests:{host:"https://srv.pixel.parsely.com",basePrefix:"${host}/plogger/?rand=${timestamp}&idsite=${apikey}&url=${ampdocUrl}&urlref=${documentReferrer}&screen=${screenWidth}x${screenHeight}%7C${availableScreenWidth}x${availableScreenHeight}%7C${screenColorDepth}&title=${title}&date=${timestamp}&ampid=${clientId(_parsely_visitor)}",
pageview:"${basePrefix}&action=pageview"},triggers:{defaultPageview:{on:"visible",request:"pageview"}},transport:{beacon:!1,xhrpost:!1,image:!0}},piano:{requests:{host:"https://api-v3.tinypass.com",basePrefix:"/api/v3",baseSuffix:"&pageview_id=${pageViewId}&rand=${random}&amp_client_id=${clientId}&aid=${aid}",pageview:"${host}${basePrefix}/page/track?url=${canonicalUrl}&referer=${documentReferrer}&content_created=${contentCreated}&content_author=${contentAuthor}&content_section=${contentSection}&timezone_offset=${timezone}&tags=${tags}&amp_url=${ampdocUrl}&screen=${screenWidth}x${screenHeight}${baseSuffix}"}},
quantcast:{vars:{labels:""},requests:{host:"https://pixel.quantserve.com/pixel",pageview:"${host};r=${random};a=${pcode};labels=${labels};fpan=;fpa=${clientId(__qca)};ns=0;ce=1;cm=;je=0;sr=${screenWidth}x${screenHeight}x${screenColorDepth};enc=n;et=${timestamp};ref=${documentReferrer};url=${canonicalUrl}"},triggers:{defaultPageview:{on:"visible",request:"pageview"}},transport:{beacon:!1,xhrpost:!1,image:!0}},adobeanalytics:{transport:{xhrpost:!1,beacon:!1,image:!0},vars:{pageName:"TITLE",host:"",
reportSuites:"",linkType:"o",linkUrl:"",linkName:""},requests:{requestPath:"/b/ss/${reportSuites}/0/amp-1.0/s${random}",basePrefix:"vid=z${clientId(adobe_amp_id)}&ndh=0&ce=${documentCharset}&pageName=${pageName}&g=${ampdocUrl}&r=${documentReferrer}&bh=${availableScreenHeight}&bw=${availableScreenWidth}&c=${screenColorDepth}&j=amp&s=${screenWidth}x${screenHeight}",pageview:"https://${host}${requestPath}?${basePrefix}",click:"https://${host}${requestPath}?${basePrefix}&pe=lnk_${linkType}&pev1=${linkUrl}&pev2=${linkName}"}},
adobeanalytics_nativeConfig:{triggers:{pageLoad:{on:"visible",request:"iframeMessage"}}},infonline:{vars:{sv:"ke",ap:"1"},transport:{beacon:!1,xhrpost:!1,image:!0},requests:{pageview:"${url}?st=${st}&sv=${sv}&ap=${ap}&co=${co}&cp=${cp}&host=${canonicalHost}&path=${canonicalPath}"},triggers:{pageview:{on:"visible",request:"pageview"}}},simplereach:{vars:{pid:"",published_at:"",authors:[],channels:[],tags:[]},requests:{host:"https://edge.simplereach.com",baseParams:"amp=true&pid=${pid}&title=${title}&url=${canonicalUrl}&date=${published_at}&authors=${authors}&channels=${categories}&tags=${tags}&referrer=${documentReferrer}&page_url=${sourceUrl}&user_id=${clientId(sr_amp_id)}&domain=${canonicalHost}",
visible:"${host}/n?${baseParams}",timer:"${host}/t?${baseParams}&t=5000&e=5000"},triggers:{visible:{on:"visible",request:"visible"},timer:{on:"timer",timerSpec:{interval:5,maxTimerLength:1200},request:"timer"}}},segment:{transport:{beacon:!1,xhrpost:!1,image:!0},vars:{anonymousId:"CLIENT_ID(segment_amp_id)"},requests:{host:"https://api.segment.io/v1/pixel",base:"?writeKey=${writeKey}&anonymousId=${anonymousId}&context.locale=${browserLanguage}&context.page.path=${canonicalPath}&context.page.url=${canonicalUrl}&context.page.referrer=${documentReferrer}&context.page.title=${title}&context.screen.width=${screenWidth}&context.screen.height=${screenHeight}",
page:"${host}/page${base}&name=${name}",track:"${host}/track${base}&event=${event}"},triggers:{page:{on:"visible",request:"page"}}},snowplow:{requests:{aaVersion:"amp-0.1",basePrefix:"https://${collectorHost}/i?url=${canonicalUrl}&page=${title}&res=${screenWidth}x${screenHeight}&stm=${timestamp}&tz=${timezone}&aid=${appId}&p=web&tv=${aaVersion}",pageView:"${basePrefix}&e=pv",structEvent:"${basePrefix}&e=se&se_ca=${structEventCategory}&se_ac=${structEventAction}&se_la=${structEventLabel}&se_pr=${structEventProperty}&se_va=${structEventValue}"},
transport:{beacon:!1,xhrpost:!1,image:!0}},webtrekk:{requests:{trackURL:"https://${trackDomain}/${trackId}/wt",parameterPrefix:"?p=432,${contentId},1,${screenWidth}x${screenHeight},${screenColorDepth},1,${timestamp},${documentReferrer},${viewportWidth}x${viewportHeight},0&tz=${timezone}&eid=${clientId(amp-wt3-eid)}&la=${browserLanguage}",parameterSuffix:"&pu=${canonicalUrl}",pageParameter:"&cp1=${pageParameter1}&cp2=${pageParameter2}&cp3=${pageParameter3}&cp4=${pageParameter4}&cp5=${pageParameter5}&cp6=${pageParameter6}&cp7=${pageParameter7}&cp8=${pageParameter8}&cp9=${pageParameter9}&cp10=${pageParameter10}",
pageCategories:"&cg1=${pageCategory1}&cg2=${pageCategory2}&cg3=${pageCategory3}&cg4=${pageCategory4}&cg5=${pageCategory5}&cg6=${pageCategory6}&cg7=${pageCategory7}&cg8=${pageCategory8}&cg9=${pageCategory9}&cg10=${pageCategory10}",pageview:"${trackURL}${parameterPrefix}${pageParameter}${pageCategories}${parameterSuffix}",actionParameter:"&ck1=${actionParameter1}&ck2=${actionParameter2}&ck3=${actionParameter3}&ck4=${actionParameter4}&ck5=${actionParameter5}",event:"${trackURL}${parameterPrefix}&ct=${actionName}${actionParameter}${parameterSuffix}"},
transport:{beacon:!1,xhrpost:!1,image:!0}},mpulse:{requests:{onvisible:"https://${beacon_url}?h.d=${h.d}&h.key=${h.key}&h.t=${h.t}&h.cr=${h.cr}&rt.start=navigation&rt.si=${clientId(amp_mpulse)}&rt.ss=${timestamp}&rt.end=${timestamp}&t_resp=${navTiming(navigationStart,responseStart)}&t_page=${navTiming(responseStart,loadEventStart)}&t_done=${navTiming(navigationStart,loadEventStart)}&nt_nav_type=${navType}&nt_red_cnt=${navRedirectCount}&nt_nav_st=${navTiming(navigationStart)}&nt_red_st=${navTiming(redirectStart)}&nt_red_end=${navTiming(redirectEnd)}&nt_fet_st=${navTiming(fetchStart)}&nt_dns_st=${navTiming(domainLookupStart)}&nt_dns_end=${navTiming(domainLookupEnd)}&nt_con_st=${navTiming(connectStart)}&nt_ssl_st=${navTiming(secureConnectionStart)}&nt_con_end=${navTiming(connectEnd)}&nt_req_st=${navTiming(requestStart)}&nt_res_st=${navTiming(responseStart)}&nt_unload_st=${navTiming(unloadEventStart)}&nt_unload_end=${navTiming(unloadEventEnd)}&nt_domloading=${navTiming(domLoading)}&nt_res_end=${navTiming(responseEnd)}&nt_domint=${navTiming(domInteractive)}&nt_domcontloaded_st=${navTiming(domContentLoadedEventStart)}&nt_domcontloaded_end=${navTiming(domContentLoadedEventEnd)}&nt_domcomp=${navTiming(domComplete)}&nt_load_st=${navTiming(loadEventStart)}&nt_load_end=${navTiming(loadEventEnd)}&v=1&http.initiator=amp&u=${sourceUrl}&amp.u=${ampdocUrl}&r2=${documentReferrer}&scr.xy=${screenWidth}x${screenHeight}"},
triggers:{onvisible:{on:"visible",request:"onvisible"}},transport:{beacon:!1,xhrpost:!1,image:!0},extraUrlParamsReplaceMap:{ab_test:"h.ab",page_group:"h.pg","custom_dimension.":"cdim.","custom_metric.":"cmet."}},linkpulse:{vars:{id:"",pageUrl:"CANONICAL_URL",title:"TITLE",section:"",channel:"amp",type:"",host:"pp.lp4.io",empty:""},requests:{base:"https://${host}",pageview:"${base}/p?i=${id}&r=${documentReferrer}&p=${pageUrl}&s=${section}&t=${type}&c=${channel}&mt=${title}&_t=amp&_r=${random}",pageload:"${base}/pl?i=${id}&ct=${domInteractiveTime}&rt=${pageDownloadTime}&pt=${pageLoadTime}&p=${pageUrl}&c=${channel}&t=${type}&s=${section}&_t=amp&_r=${random}",
ping:"${base}/u?i=${id}&u=${clientId(_lp4_u)}&p=${pageUrl}&uActive=true&isPing=yes&c=${channel}&t=${type}&s=${section}&_t=amp&_r=${random}"},triggers:{pageview:{on:"visible",request:"pageview"},pageload:{on:"visible",request:"pageload"},ping:{on:"timer",timerSpec:{interval:30,maxTimerLength:7200},request:"ping"}},transport:{beacon:!1,xhrpost:!1,image:!0}}};nb.infonline.triggers.pageview.iframePing=!0;nb.adobeanalytics_nativeConfig.triggers.pageLoad.iframePing=!0;
nb.oewa.triggers.pageview.iframePing=!0;function ob(a){return void 0===a||"number"==typeof a&&0<=Math.sign(a)}function pb(a){return void 0===a||"number"==typeof a&&0<=Math.sign(a)&&100>=a}
function qb(a){if(!a.visibilitySpec)return!0;var b=a.visibilitySpec;a=b.selector;if(!a||"#"!=a[0]&&0!=a.indexOf("amp-"))return q().error("Analytics.Visibility",'Visibility spec requires an id selector or a tag name starting with "amp-"'),!1;var c=b.continuousTimeMax,d=b.continuousTimeMin,e=b.totalTimeMax,f=b.totalTimeMin;return ob(d)&&ob(c)&&ob(f)&&ob(e)?c<d||e<f?(q().warn("Max value in timing conditions should be more than the min value."),!1):pb(b.visiblePercentageMax)&&pb(b.visiblePercentageMin)?
b.visiblePercentageMax<b.visiblePercentageMin?(q().error("Analytics.Visibility","visiblePercentageMax should be greater than visiblePercentageMin"),!1):!0:(q().error("Analytics.Visibility","visiblePercentage conditions should be between 0 and 100."),!1):(q().error("Analytics.Visibility","Timing conditions should be positive integers when specified."),!1)}
function rb(a,b,c){return b?"closest"==c?la(b,a):"scope"==c?b.parentElement.querySelector(a):"#"==a[0]?b.ownerDocument.getElementById(a.slice(1)):null:null}
function sb(a){this.A=a;this.P=Object.create(null);this.K=t(a,"timer");this.R=[];this.ca=this.L.bind(this);this.ta=this.qa.bind(this);this.pa=this.ma=!1;a=this.A.document;if(a.nodeType){var b=(a.ownerDocument||a).defaultView,b=b.__AMP_TOP||b;a=da(b,b,"ampdoc").getAmpDoc(a)}this.za=(a=a.isSingleDoc()?a.win:a)&&a.services&&a.services.resources&&a.services.resources.obj;this.G=null;this.S=Infinity;this.X=!1;this.B=z(this.A);this.aa=this.$=!this.B.isVisible()}
function tb(a){if(!a.ma){var b=t(a.A,"viewport");b.onScroll(a.ca);b.onChanged(a.ca);a.ma=!0}}
sb.prototype.listenOnce=function(a,b,c,d){var e=this,f=a.selector,g=rb(f,d,a.selectionMethod);q().assert(g,"Element not found for visibilitySpec: "+f);f=null;try{f=this.za.getResourceForElement(g)}catch(m){q().assert(f,"Visibility tracking not supported on element: ",g)}var k=f.getId();tb(this);this.pa||(this.B.onVisibilityChanged(this.ta),this.pa=!0,this.qa());this.P[k]=this.P[k]||[];var h={};h.tL=Date.now();this.P[k].push({config:a,callback:b,state:h,shouldBeVisible:c});this.R.push(f);null==this.G&&
(this.G=this.K.delay(function(){e.L()},20))};sb.prototype.qa=function(){var a=this.B.getVisibilityState();if("hidden"==a||"paused"==a||"inactive"==a)this.aa=!0;this.L()};
sb.prototype.L=function(){var a=this;null!=this.G&&(this.K.cancel(this.G),this.G=null);this.timeToWait=Infinity;for(var b=[],c=this.R.length-1;0<=c;c--){var d=this.R[c];if(d.hasLoadedOnce()){for(var e=d.element.getIntersectionChangeEntry(),f=e.intersectionRect,g=e.boundingClientRect,k=0==g.height*g.width?0:f.width*f.height*100/(g.height*g.width),h=this.P[d.getId()],d=h.length-1;0<=d;d--){var m=h[d].shouldBeVisible;ub(this,k,h[d],m)&&this.B.isVisible()==m&&(vb(this,h[d].state,e.rootBounds,g,f),h[d].callback(h[d].state),
h.splice(d,1))}0==h.length&&this.R.splice(c,1)}else b.push(d.loadedOnce())}null==this.G&&Infinity>this.S&&0<this.S&&(this.G=this.K.delay(function(){a.L()},this.S));0<b.length&&!this.X&&(Promise.race(b).then(function(){a.X=!1;a.L()}),this.X=!0)};
function ub(a,b,c,d){var e=c.config,f=c.state||{};0<b&&(f.firstSeenTime=f.firstSeenTime||Date.now()-f.tL,f.lastSeenTime=Date.now()-f.tL);var g=f.iV,k=Date.now()-f.lU,h=e.visiblePercentageMin,m=e.visiblePercentageMax;f.iV=void 0===h&&void 0===m||b>(h||0)&&b<=(m||100)?!0:!1;f.iV&&g?wb(f,b,k):!f.iV&&g?(f.maxContinuousVisibleTime=Math.max(f.maxContinuousVisibleTime,f.cT+k),f.lU=-1,f.totalVisibleTime+=k,f.cT=0,f.lastVisibleTime=Date.now()-f.tL):f.iV&&!g&&(f.fistVisibleTime=f.fistVisibleTime||Date.now()-
f.tL,wb(f,b,0));var w=e.continuousTimeMin?e.continuousTimeMin-f.cT:Infinity,r=e.totalTimeMin?e.totalTimeMin-f.totalVisibleTime:Infinity;a.S=Math.min(a.timeToWait,0<w?w:Infinity,0<r?r:Infinity);c.state=f;return(d&&f.iV||!d)&&(void 0===e.totalTimeMin||f.totalVisibleTime>=e.totalTimeMin)&&(void 0===e.totalTimeMax||f.totalVisibleTime<=e.totalTimeMax)&&(void 0===e.continuousTimeMin||f.cT>=e.continuousTimeMin)&&(void 0===e.continuousTimeMax||f.cT<=e.continuousTimeMax)}
function wb(a,b,c){a.lU=Date.now();a.totalVisibleTime=void 0!==a.totalVisibleTime?a.totalVisibleTime+c:0;a.cT=void 0!==a.cT?a.cT+c:0;a.maxContinuousVisibleTime=void 0!==a.maxContinuousVisibleTime?Math.max(a.maxContinuousVisibleTime,a.cT):0;a.minVisiblePercentage=a.minVisiblePercentage?Math.min(a.minVisiblePercentage,b):101;a.maxVisiblePercentage=a.maxVisiblePercentage?Math.max(a.maxVisiblePercentage,b):-1;a.lastVisibleTime=Date.now()-a.tL}
function vb(a,b,c,d,e){var f=a.A.performance;b.elementX=c.left+d.left;b.elementY=c.top+d.top;b.elementWidth=d.width;b.elementHeight=d.height;b.totalTime=f&&f.timing&&f.timing.domInteractive?Date.now()-f.timing.domInteractive:"";var g={top:0,height:c.height,left:0,width:c.width},k={top:e.top,left:e.left,width:d.width,height:d.height};a:{var h=g,m=k;e=Math.max(h.left,m.left);var w=Math.min(h.left+h.width,m.left+m.width);if(e<=w){var r=Math.max(h.top,m.top),h=Math.min(h.top+h.height,m.top+m.height);
if(r<=h){w-=e;h-=r;e={left:e,top:r,width:w,height:h,bottom:r+h,right:e+w};break a}}e=null}var p=e;b.loadTimeVisibility=null!=p?Math.round(p.width*p.height*1E4/(d.width*d.height))/100:0;b.minVisiblePercentage=Math.round(100*b.minVisiblePercentage)/100;b.maxVisiblePercentage=Math.round(100*b.maxVisiblePercentage)/100;b.backgrounded=a.aa?"1":"0";b.backgroundedAtStart=a.$?"1":"0";delete b.cT;delete b.lU;delete b.iV;delete b.tL;for(var x in b)b.hasOwnProperty(x)&&(b[x]=String(b[x]))};var na=/^vars(.+)/;function V(a,b){this.type=a;this.vars=b||Object.create(null)}function W(a){var b=this;this.A=a;this.C="Analytics.Instrumentation";this.K=t(a,"timer");this.B=z(a);this.D=t(a,"viewport");this.da=!1;this.ea=new A;this.la=!1;this.na=new A;this.U={};this.H={};this.K.delay(function(){b.H=void 0},1E4)}
W.prototype.addListener=function(a,b,c){var d=a.on;if("visible"===d)xb(this,b,a,"visible",c);else if("click"===d)a.selector?(this.da||(this.da=!0,this.A.document.documentElement.addEventListener("click",this.xa.bind(this))),this.ea.add(yb(this,b,a.selector))):q().error(this.C,"Missing required selector on click trigger");else if("scroll"===d)a.scrollSpec?(zb(this,a.scrollSpec,b),a=this.D.getSize(),this.ia({top:this.D.getScrollTop(),left:this.D.getScrollLeft(),width:a.width,height:a.height})):q().error(this.C,
"Missing scrollSpec on scroll trigger.");else if("timer"===d)Ab(this,a.timerSpec)&&Bb(this,b,a.timerSpec);else if("hidden"===d)xb(this,b,a,"hidden",c);else{var e=this.U[d];e||(e=new A,this.U[d]=e);e.add(b);if(this.H){var f=this.H[d];f&&this.K.delay(function(){f.forEach(function(a){b(a)})},1)}}};W.prototype.triggerEvent=function(a){var b=new V(a);if(this.H){var c=this.H[b.type];c||(c=[],this.H[b.type]=c);c.push(b)}(a=this.U[a])&&a.fire(b)};
function xb(a,b,c,d,e){var f="visible"==d,g=c.visibilitySpec;if(g)qb(c)&&oa(a.A,"visibility","amp-analytics").then(function(a){a.listenOnce(g,function(a){var c=rb(g.selector,e,g.selectionMethod);if(c){var c=ma(c),f;for(f in c)a[f]=c[f]}b(new V(d,a))},f,e)});else if(a.B.isVisible()==f)b(new V(d)),c.called=!0;else a.B.onVisibilityChanged(function(){c.called||a.B.isVisible()!=f||(b(new V(d)),c.called=!0)})}W.prototype.xa=function(a){this.ea.fire(a)};W.prototype.ia=function(a){this.na.fire(a)};
function yb(a,b,c){return function(d){d=d.target;if("*"===c||Cb(a,d,c))b(new V("click",ma(d)));else for(;null!=d.parentElement&&"BODY"!=d.parentElement.tagName;)if(d=d.parentElement,Cb(a,d,c)){b(new V("click",ma(d)));break}}}
function zb(a,b,c){if(Array.isArray(b.verticalBoundaries)||Array.isArray(b.horizontalBoundaries)){a.la||(a.la=!0,a.D.onChanged(a.ia.bind(a)));var d=function(a,b,d){if(b)for(var e in a)if(!(!a.hasOwnProperty(e)||e>b||a[e])){a[e]=!0;var f=Object.create(null);f[d]=e;c(new V("scroll",f))}},e=Db(a,b.verticalBoundaries),f=Db(a,b.horizontalBoundaries);a.na.add(function(b){d(e,100*(b.top+b.height)/a.D.getScrollHeight(),"verticalScrollBoundary");d(f,100*(b.left+b.width)/a.D.getScrollWidth(),"horizontalScrollBoundary")})}else q().error(a.C,
"Boundaries are required for the scroll trigger to work.")}function Db(a,b){var c={};if(!b||!Array.isArray(b))return c;for(var d=0;d<b.length;d++){var e=b[d];if("number"!==typeof e||!isFinite(e)){q().error(a.C,"Scroll trigger boundaries must be finite.");break}e=Math.min(5*Math.round(e/5),100);c[e]=!1}return c}
function Cb(a,b,c){try{var d=b.matches||b.webkitMatchesSelector||b.mozMatchesSelector||b.msMatchesSelector||b.oMatchesSelector;if(d)return d.call(b,c);for(var e=a.A.document.querySelectorAll(c),f=e.length;0<f--&&e.item(f)!=b;);return-1<f}catch(g){q().error(a.C,"Bad query selector.",c,g)}return!1}
function Ab(a,b){if(b){if(b.hasOwnProperty("interval"))return"number"!==typeof b.interval||.5>b.interval?(q().error(a.C,"Bad timer interval specification"),!1):b.hasOwnProperty("maxTimerLength")&&("number"!==typeof b.maxTimerLength||0>=b.maxTimerLength)?(q().error(a.C,"Bad maxTimerLength specification"),!1):!0;q().error(a.C,"Timer interval specification required");return!1}q().error(a.C,"Bad timer specification");return!1}
function Bb(a,b,c){var d=a.A.setInterval(b.bind(null,new V("timer")),1E3*c.interval);b(new V("timer"));var e=c.maxTimerLength||7200;a.A.setTimeout(a.A.clearInterval.bind(a.A,d),1E3*e)}function Eb(a){return u(a,"amp-analytics-instrumentation",W)};function Fb(a){this.win=a;this.T=null;this.V=Object.create(null)}Fb.prototype.get=function(a,b,c){var d=this,e;e="string"==typeof a?{scope:a}:a;q().assert(/^[a-zA-Z0-9-_]+$/.test(e.scope),"The client id name must only use the characters [a-zA-Z0-9-_]+\nInstead found: %s",e.scope);return b.then(function(){return z(d.win).whenFirstVisible()}).then(function(){return Gb(d,e,c||b)})};
function Gb(a,b,c){var d=y(a.win.location.href);return ya(d)?Promise.all([Hb(a,c),B(a.win)]).then(function(a){var c=a[0],g=a[1];return g.sha384Base64(c+Ib(d)+b.scope)}):Jb(a,b,c)}function Kb(a,b,c){var d=Date.now()+31536E6;a:{var e=b,f=d,g={highestAvailableDomain:!0};if(g&&g.highestAvailableDomain)for(var g=a.location.hostname.split("."),k=g[g.length-1],h=g.length-2;0<=h;h--)if(k=g[h]+"."+k,Ba(a,e,c,f,k),Aa(a,e)==c)break a;Ba(a,e,c,f,void 0)}}
function Jb(a,b,c){var d=a.win,e=b.scope,f=Aa(d,e);if(!f&&!b.createCookieIfNotPresent)return Promise.resolve(null);if(a.V[e])return a.V[e];if(f)return/^amp-/.test(f)&&Kb(d,e,f),Promise.resolve(f);var g=B(d).then(function(a){return a.sha384Base64(Lb(d))}).then(function(a){return"amp-"+a});Promise.all([g,c]).then(function(a){var b=a[0],c=Aa(d,e);c||Kb(d,e,b)});return a.V[e]=g}
function Ib(a){q().assert(ya(a),"Expected proxy origin %s",a.origin);"string"==typeof a&&(a=y(a));if(ya(a)){var b=a.pathname.split("/"),c=b[1];q().assert("c"==c||"v"==c,"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);q().assert(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");c=(c=a.search)&&"?"!=c?(c=c.replace(ua,"").replace(/^[?&]/,""))?"?"+c:"":"";a=b+c+(a.hash||"")}else a=a.href;
return y(a).origin}function Hb(a,b){if(a.T)return a.T;var c=a.win;return a.T=Mb(c).then(function(a){var e=!1,f;a&&!Nb(a)?(f=Promise.resolve(a.cid),Ob(a)&&(e=!0)):(f=B(c).then(function(a){return a.sha384Base64(Lb(c))}),e=!0);e&&f.then(function(a){Pb(c,b,a)});return f})}function Pb(a,b,c){var d=z(a);d.isIframed()?d.baseCid(Qb(c)):b.then(function(){try{a.localStorage.setItem("amp-cid",Qb(c))}catch(b){}})}function Qb(a){return JSON.stringify({time:Date.now(),cid:a})}
function Mb(a){var b;try{b=a.localStorage.getItem("amp-cid")}catch(d){}a=z(a);var c=Promise.resolve(b);!b&&a.isIframed()&&(c=a.baseCid());return c.then(function(a){if(!a)return null;var b=JSON.parse(a);return{time:b.time,cid:b.cid}})}function Nb(a){var b=a.time,c=Date.now();return b+31536E6<c}function Ob(a){a=a.time;var b=Date.now();return a+864E5<b}
function Lb(a){var b;a.crypto&&a.crypto.getRandomValues?(b=new Uint8Array(16),a.crypto.getRandomValues(b)):b=null;return b?b:String(a.location.href+Date.now()+a.Math.random()+a.screen.width+a.screen.height)};function Rb(a){this.oa=a.crypto?a.crypto.subtle||a.crypto.webkitSubtle||null:null}Rb.prototype.sha384=function(a){if(this.oa)try{return this.oa.digest({name:"SHA-384"},a instanceof Uint8Array?a:za(a)).then(function(a){return[].slice.call(new Uint8Array(a))},function(b){b.message&&0>b.message.indexOf("secure origin")&&ba().error("Crypto","SubtleCrypto failed, fallback to closure lib.",b);return ampSha384Digest(a)})}catch(b){ba().error("Crypto","SubtleCrypto failed, fallback to closure lib.",b)}return Promise.resolve(ampSha384Digest(a))};
Rb.prototype.sha384Base64=function(a){return this.sha384(a).then(function(a){return ampBase64(a)})};Rb.prototype.uniform=function(a){return this.sha384(a).then(function(a){for(var c=0,d=2;0<=d;d--)c=(c+a[d])/256;return c})};function Sb(a){var b=new Image;b.src=a;b.width=1;b.height=1;Ea(b).then(function(){}).catch(function(){q().warn("amp-analytics.Transport","Response unparseable or failed to send image request",a)})}function Tb(a,b){if(!a.XMLHttpRequest)return!1;var c=new a.XMLHttpRequest;if(!("withCredentials"in c))return!1;c.open("POST",b,!0);c.withCredentials=!0;c.setRequestHeader("Content-Type","text/plain");c.onreadystatechange=function(){};c.send("");return!0}
function Ub(a,b){xa(b);var c=a.document.createElement("iframe");c.style.display="none";c.onload=c.onerror=function(){t(a,"timer").delay(function(){var a=c;a.parentElement&&a.parentElement.removeChild(a)},5E3)};q().assert(y(b).origin!=y(a.location.href).origin,"Origin of iframe request must not be equal to the document origin. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.");c.setAttribute("amp-analytics","");c.setAttribute("sandbox","allow-scripts allow-same-origin");
c.src=b;a.document.body.appendChild(c)};(function(a){return u(a,"activity",kb)})(AMP.win);(function(a){return u(a,"cid",Fb)})(AMP.win);(function(a){return u(a,"crypto",Rb)})(AMP.win);(function(a){return u(a,"visibility",sb)})(AMP.win);Eb(AMP.win);function Vb(a){AMP.BaseElement.apply(this,arguments)}aa(Vb,AMP.BaseElement);l=Vb.prototype;l.getPriority=function(){return 1};l.isAlwaysFixed=function(){return!0};l.isLayoutSupported=function(){return!0};l.createdCallback=function(){this.ja=nb};
l.buildCallback=function(){var a=this;this.element.setAttribute("aria-hidden","true");this.fa=this.element.getAttribute("data-consent-notification-id");this.ga=Promise.resolve();null!=this.fa&&(this.ga=oa(this.win,"userNotificationManager","amp-user-notification").then(function(b){return b.get(a.fa)}))};l.layoutCallback=function(){var a=this.element,b=!1;void 0===b&&(b="none"==a.style.display);a.style.display=b?"":"none";this.Fa=null;this.J={};this.ka={};return this.ga.then(this.ua.bind(this)).then(this.ya.bind(this))};
l.ya=function(){var a=this;this.w=Wb(this);if(Xb(this))return X(this),Promise.resolve();Yb(this);if(!this.w.triggers)return q().error(X(this),"No triggers were found in the config. No analytics data will be sent."),Promise.resolve();Zb(this,this.w.extraUrlParams,this.w.extraUrlParamsReplaceMap);var b=[],c={},d;for(d in this.w.triggers){if(this.w.triggers.hasOwnProperty(d)){c.trigger=this.w.triggers[d];if(!c.trigger){q().error(X(this),"Trigger should be an object: ",d);continue}if(!c.trigger.on||!c.trigger.request){q().error(X(this),
'"on" and "request" attributes are required for data to be collected.');continue}Zb(this,c.trigger.extraUrlParams,this.w.extraUrlParamsReplaceMap);b.push($b(this,c.trigger).then(function(b){return function(c){if(c){b.trigger.selector&&(b.trigger.selector=Y(a,b.trigger.selector,b.trigger,void 0,void 0,!1));c=b.trigger;var d=a.va.bind(a,b.trigger),k=a.element;Eb(a.win).addListener(c,d,k)}}}(c)))}c={trigger:c.trigger}}return Promise.all(b)};
function Zb(a,b,c){if(b&&c){var d=0,e;for(e in c){if(16<++d){q().error(X(a),"More than 16 extraUrlParamsReplaceMap rules aren't allowed; Skipping the rest");break}for(var f in b){var g=f.replace(e,c[e]);if(f!=g){var k=b[f];delete b[f];b[g]=k}}}}}
l.ua=function(){var a=this,b=this.element.getAttribute("config");if(!b)return Promise.resolve();xa(b);X(this);var c={requireAmpResponseSourceOrigin:!0};this.element.hasAttribute("data-credentials")&&(c.credentials=this.element.getAttribute("data-credentials"));var d=this.win;return t(d,"url-replace").expandAsync(b).then(function(a){b=a;return t(d,"xhr").fetchJson(b,c)}).then(function(b){a.ka=b;X(a)},function(c){q().error(X(a),"Error loading remote config: ",b,c)})};
function Wb(a){var b=a.getInlineConfigNoInline(),c={vars:{requestCount:0}},d=a.ja["default"]||{},e=a.ja[a.element.getAttribute("type")]||{};Z(a,d,c);Z(a,e,c,!0);Z(a,b,c);Z(a,a.ka,c);return c}
l.getInlineConfigNoInline=function(){var a={};try{var b=this.element.children;if(1==b.length){var c=b[0];"SCRIPT"==c.tagName&&"APPLICATION/JSON"==c.getAttribute("type").toUpperCase()?a=JSON.parse(b[0].textContent):q().error(X(this),'The analytics config should be put in a <script> tag with type="application/json"')}else 1<b.length&&q().error(X(this),"The tag should contain only one <script> child.")}catch(d){q().error(X(this),"Analytics config could not be parsed. Is it in a valid JSON format?",d)}return a};
function Xb(a){if(!a.w.optout)return!1;var b=a.w.optout.split(".");a=a.win;for(var c=0;c<b.length;c++){if(!a)return!1;a=a[b[c]]}return a()}function Yb(a){var b={};if(a.w&&a.w.requests){for(var c in a.w.requests)a.w.requests.hasOwnProperty(c)&&(b[c]=a.w.requests[c]);a.J=b;for(var d in a.J)a.J[d]=ra(a.J[d],function(b){return a.J[b]||"${"+b+"}"},5)}else ba().error(X(a),"No request strings defined. Analytics data will not be sent from this page.")}
l.va=function(a,b){for(var c=Array.isArray(a.request)?a.request:[a.request],d=[],e=0;e<c.length;e++)d.push(ac(this,this.J[c[e]],a,b));return Promise.all(d)};
function ac(a,b,c,d){if(!b)return q().error(X(a),"Ignoring event. Request string not found: ",c.request),Promise.resolve();if(a.w.extraUrlParams||c.extraUrlParams){var e=Object.create(null);Object.assign(e,a.w.extraUrlParams,c.extraUrlParams);for(var f in e)"string"==typeof e[f]&&(e[f]=Y(a,e[f],c,d));if(0<=b.indexOf("${extraUrlParams}")){var g=va("",wa(e)).substr(1);b=b.replace("${extraUrlParams}",g)}else b=va(b,wa(e))}a.w.vars.requestCount++;b=Y(a,b,c,d);return t(a.win,"url-replace").expandAsync(b).then(function(b){if(b)if(c.iframePing)q().assert("visible"==
c.on,"iframePing is only available on page view requests."),Ub(a.win,b);else{var d=a.win,e=a.w.transport||{};xa(b);var f=y(b).search,g=Object.create(null);if(f){if(0==f.indexOf("?")||0==f.indexOf("#"))f=f.substr(1);for(var f=f.split("&"),p=0;p<f.length;p++){var x=f[p],O=x.indexOf("="),K;-1!=O?(K=decodeURIComponent(x.substring(0,O)).trim(),x=decodeURIComponent(x.substring(O+1)).trim()):(K=decodeURIComponent(x).trim(),x="");K&&(g[K]=x)}}q().assert(!("__amp_source_origin"in g),"Source origin is not allowed in %s",
b);e.beacon&&d.navigator.sendBeacon&&d.navigator.sendBeacon(b,"")||e.xhrpost&&Tb(d,b)||(e.image?Sb(b):q().warn("amp-analytics.Transport","Failed to send request",b,e))}else q().error(X(a),"Request not sent. Contents empty.");return b})}
function $b(a,b){var c=b.sampleSpec,d=Promise.resolve(!0);if(!c)return d;if(!c.sampleOn)return console.error(X(a),"Invalid sampleOn value."),d;var e=parseFloat(c.threshold);if(0<=e&&100>=e){b=Y(a,c.sampleOn,b);var f=t(a.win,"url-replace").expandAsync(b),g=B(a.win);return Promise.all([f,g]).then(function(a){return a[1].uniform(a[0])}).then(function(a){return 100*a<c.threshold})}console.error(X(a),"Invalid threshold for sampling.");return d}
function Y(a,b,c,d,e,f){e=void 0===e?2:e;f=void 0===f?!0:f;return 0>e?(q().error("Maximum depth reached while expanding variables. Please ensure that the variables are not recursive."),b):ra(b,function(b){var k=b.match(/([^(]*)(\([^)]*\))?/),h=k[1];b=k[2]||"";var m=d&&d.vars&&d.vars[h]||c.vars&&c.vars[h]||a.w.vars&&a.w.vars[h]||"";"string"==typeof m&&(m=Y(a,m,c,d,e-1));f?(h=m,h=Array.isArray(h)?h.map(encodeURIComponent).join(","):encodeURIComponent(h)):h=m;return h+b})}
function X(a){return"AmpAnalytics "+(a.element.getAttribute("id")||"<unknown id>")}function Z(a,b,c,d){if(null===c||void 0===c)c={};for(var e in b)q().assert(d||"iframePing"!=e,"iframePing config is only available to vendor config."),b.hasOwnProperty(e)&&(Array.isArray(b[e])?(Array.isArray(c[e])||(c[e]=[]),c[e]=Z(a,b[e],c[e],d)):"[object Object]"===ca.call(b[e])?("[object Object]"===ca.call(c[e])||(c[e]={}),c[e]=Z(a,b[e],c[e],d)):c[e]=b[e]);return c}AMP.registerElement("amp-analytics",Vb);
})});
//# sourceMappingURL=amp-analytics-0.1.js.map
