(window.AMP = window.AMP || []).push({n:"amp-mustache", f:(function(AMP) {var process={env:{NODE_ENV:"production"}};function ca(b,a){function c(){}c.prototype=a.prototype;b.prototype=new c;b.prototype.constructor=b;for(var e in a)if(Object.defineProperties){var h=Object.getOwnPropertyDescriptor(a,e);h&&Object.defineProperty(b,e,h)}else b[e]=a[e]};(new Date).getTime();var da=self.log=self.log||{user:null,dev:null};function w(){if(da.user)return da.user;throw Error("failed to call initLogConstructor");};var ea=(self.AMP_CONFIG||{}).cdnUrl||"https://cdn.ampproject.org";var B,fa,ga=/[?&]amp_js[^&]*/;
function I(b){B||(B=self.document.createElement("a"),fa=self.UrlCache||(self.UrlCache=Object.create(null)));var a=fa[b];if(a)return a;B.href=b;B.protocol||(B.href=B.href);var c={href:B.href,protocol:B.protocol,host:B.host,hostname:B.hostname,port:"0"==B.port?"":B.port,pathname:B.pathname,search:B.search,hash:B.hash,origin:null};"/"!==c.pathname[0]&&(c.pathname="/"+c.pathname);if("http:"==c.protocol&&80==c.port||"https:"==c.protocol&&443==c.port)c.port="",c.host=c.hostname;c.origin=B.origin&&"null"!=
B.origin?B.origin:"data:"!=c.protocol&&c.host?c.protocol+"//"+c.host:c.href;return fa[b]=c}function ha(b){"string"==typeof b&&(b=I(b));var a=b.pathname.split("/")[1];return b.origin==ea||0==b.origin.indexOf("http://localhost:")&&("c"==a||"v"==a)}function la(b,a){"string"==typeof a&&(a=I(a));return"function"==typeof URL?(new URL(b,a.href)).toString():ma(b,a)}
function ma(b,a){"string"==typeof a&&(a=I(a));b=b.replace(/\\/g,"/");var c=I(b);if(0==b.toLowerCase().indexOf(c.protocol))return c.href;if(0==b.indexOf("//"))return a.protocol+b;if(0==b.indexOf("/"))return a.origin+b;var e=a.pathname.split("/");return a.origin+(1<e.length?e.slice(0,e.length-1).join("/"):"")+"/"+b};function L(b){w().assert(0<b.length,"Srcset must have at least one source");this.f=b;var a=!1,c=!1;for(b=0;b<this.f.length;b++){var e=this.f[b];w().assert((e.width||e.dpr)&&(!e.width||!e.dpr),"Either dpr or width must be specified");a=a||!!e.width;c=c||!!e.dpr}w().assert(!a||!c,"Srcset cannot have both width and dpr sources");a?this.f.sort(ua):this.f.sort(va);this.C=a;this.B=c}
L.prototype.select=function(b,a){var c=-1;if(this.C)for(var c=-1,e=1E6,h=1E6,l=0;l<this.f.length;l++){var f=this.f[l],f=f.width?f.width/a:e/2,e=Math.min(e,f),f=Math.abs((f-b)/b-.2);f<h&&(h=f,c=l)}else if(this.B){b=-1;c=1E6;for(e=0;e<this.f.length;e++)h=Math.abs((this.f[e].dpr||1)-a),h<c&&(c=h,b=e);c=b}return-1!=c?this.f[c]:this.getLast()};L.prototype.getLast=function(){return this.f[this.f.length-1]};L.prototype.getSources=function(){return this.f};
L.prototype.stringify=function(){for(var b=[],a=0;a<this.f.length;a++){var c=this.f[a];c.width?b.push(c.url+" "+c.width+"w"):c.dpr?b.push(c.url+" "+c.dpr+"x"):b.push(""+c.url)}return b.join(", ")};function ua(b,a){w().assert(b.width!=a.width,"Duplicate width: %s",b.width);return a.width-b.width}function va(b,a){w().assert(b.dpr!=a.dpr,"Duplicate dpr: %s",b.dpr);return a.dpr-b.dpr};var wa=function(){function b(b){var a=(""+b).match(n);return a?new d(r(a[1]),r(a[2]),r(a[3]),r(a[4]),r(a[5]),r(a[6]),r(a[7])):null}function a(b,a,y,f,l,M,n){b=new d(e(b,g),e(a,g),c(y),0<f?f.toString():null,e(l,J),null,c(n));M&&("string"===typeof M?b.setRawQuery(M.replace(/[^?&=0-9A-Za-z_\-~.%]/g,h)):b.setAllParameters(M));return b}function c(b){return"string"==typeof b?encodeURIComponent(b):null}function e(b,a){return"string"==typeof b?encodeURI(b).replace(a,h):null}function h(b){var a=b.charCodeAt(0);
return"%"+"0123456789ABCDEF".charAt(a>>4&15)+"0123456789ABCDEF".charAt(a&15)}function l(b){return b.replace(/(^|\/)\.(?:\/|$)/g,"$1").replace(/\/{2,}/g,"/")}function f(b){if(null===b)return null;b=l(b);for(var a=F,c;(c=b.replace(a,"$1"))!=b;b=c);return b}function E(b,a){var c=b.clone(),d=a.hasScheme();d?c.setRawScheme(a.getRawScheme()):d=a.hasCredentials();d?c.setRawCredentials(a.getRawCredentials()):d=a.hasDomain();d?c.setRawDomain(a.getRawDomain()):d=a.hasPort();var h=a.getRawPath(),e=f(h);if(d)c.setPort(a.getPort()),
e=e&&e.replace(v,"");else if(d=!!h){if(47!==e.charCodeAt(0))var g=f(c.getRawPath()||"").replace(v,""),l=g.lastIndexOf("/")+1,e=f((l?g.substring(0,l):"")+f(h)).replace(v,"")}else e=e&&e.replace(v,""),e!==h&&c.setRawPath(e);d?c.setRawPath(e):d=a.hasQuery();d?c.setRawQuery(a.getRawQuery()):d=a.hasFragment();d&&c.setRawFragment(a.getRawFragment());return c}function d(b,a,c,d,e,f,h){this.o=b;this.j=a;this.l=c;this.v=d;this.h=e;this.g=f;this.m=h;this.c=null}function r(b){return"string"==typeof b&&0<b.length?
b:null}var z=/(\/|^)(?:[^./][^/]*|\.{2,}(?:[^./][^/]*)|\.{3,}[^/]*)\/\.\.(?:\/|$)/,F=new RegExp(z),v=/^(?:\.\.\/)*(?:\.\.$)?/;d.prototype.toString=function(){var b=[];null!==this.o&&b.push(this.o,":");null!==this.l&&(b.push("//"),null!==this.j&&b.push(this.j,"@"),b.push(this.l),null!==this.v&&b.push(":",this.v.toString()));null!==this.h&&b.push(this.h);null!==this.g&&b.push("?",this.g);null!==this.m&&b.push("#",this.m);return b.join("")};d.prototype.clone=function(){return new d(this.o,this.j,this.l,
this.v,this.h,this.g,this.m)};d.prototype.getScheme=function(){return this.o&&decodeURIComponent(this.o).toLowerCase()};d.prototype.getRawScheme=function(){return this.o};d.prototype.setScheme=function(b){this.o=e(b,g);return this};d.prototype.setRawScheme=function(b){this.o=b?b:null;return this};d.prototype.hasScheme=function(){return null!==this.o};d.prototype.getCredentials=function(){return this.j&&decodeURIComponent(this.j)};d.prototype.getRawCredentials=function(){return this.j};d.prototype.setCredentials=
function(b){this.j=e(b,g);return this};d.prototype.setRawCredentials=function(b){this.j=b?b:null;return this};d.prototype.hasCredentials=function(){return null!==this.j};d.prototype.getDomain=function(){return this.l&&decodeURIComponent(this.l)};d.prototype.getRawDomain=function(){return this.l};d.prototype.setDomain=function(b){return this.setRawDomain(b&&encodeURIComponent(b))};d.prototype.setRawDomain=function(b){this.l=b?b:null;return this.setRawPath(this.h)};d.prototype.hasDomain=function(){return null!==
this.l};d.prototype.getPort=function(){return this.v&&decodeURIComponent(this.v)};d.prototype.setPort=function(b){if(b){b=Number(b);if(b!==(b&65535))throw Error("Bad port number "+b);this.v=""+b}else this.v=null;return this};d.prototype.hasPort=function(){return null!==this.v};d.prototype.getPath=function(){return this.h&&decodeURIComponent(this.h)};d.prototype.getRawPath=function(){return this.h};d.prototype.setPath=function(b){return this.setRawPath(e(b,J))};d.prototype.setRawPath=function(b){b?
(b=String(b),this.h=!this.l||/^\//.test(b)?b:"/"+b):this.h=null;return this};d.prototype.hasPath=function(){return null!==this.h};d.prototype.getQuery=function(){return this.g&&decodeURIComponent(this.g).replace(/\+/g," ")};d.prototype.getRawQuery=function(){return this.g};d.prototype.setQuery=function(b){this.c=null;this.g=c(b);return this};d.prototype.setRawQuery=function(b){this.c=null;this.g=b?b:null;return this};d.prototype.hasQuery=function(){return null!==this.g};d.prototype.setAllParameters=
function(b){if("object"===typeof b&&!(b instanceof Array)&&(b instanceof Object||"[object Array]"!==Object.prototype.toString.call(b))){var a=[],c=-1,d;for(d in b){var e=b[d];"string"===typeof e&&(a[++c]=d,a[++c]=e)}b=a}this.c=null;for(var f=[],h="",g=0;g<b.length;)d=b[g++],e=b[g++],f.push(h,encodeURIComponent(d.toString())),h="&",e&&f.push("=",encodeURIComponent(e.toString()));this.g=f.join("");return this};d.prototype.w=function(){if(!this.c){var b=this.g;if(b){for(var a=b.split(/[&\?]/),b=[],d=
-1,c=0;c<a.length;++c){var e=a[c].match(/^([^=]*)(?:=(.*))?$/);b[++d]=decodeURIComponent(e[1]).replace(/\+/g," ");b[++d]=decodeURIComponent(e[2]||"").replace(/\+/g," ")}this.c=b}else this.c=[]}};d.prototype.setParameterValues=function(b,a){"string"===typeof a&&(a=[a]);this.w();for(var d=0,c=this.c,e=[],f=0;f<c.length;f+=2)b===c[f]?d<a.length&&e.push(b,a[d++]):e.push(c[f],c[f+1]);for(;d<a.length;)e.push(b,a[d++]);this.setAllParameters(e);return this};d.prototype.removeParameter=function(b){return this.setParameterValues(b,
[])};d.prototype.getAllParameters=function(){this.w();return this.c.slice(0,this.c.length)};d.prototype.getParameterValues=function(b){this.w();for(var a=[],d=0;d<this.c.length;d+=2)b===this.c[d]&&a.push(this.c[d+1]);return a};d.prototype.getParameterMap=function(){this.w();for(var b={},a=0;a<this.c.length;a+=2){var d=this.c[a++],c=this.c[a++];d in b?b[d].push(c):b[d]=[c]}return b};d.prototype.getParameterValue=function(b){this.w();for(var a=0;a<this.c.length;a+=2)if(b===this.c[a])return this.c[a+
1];return null};d.prototype.getFragment=function(){return this.m&&decodeURIComponent(this.m)};d.prototype.getRawFragment=function(){return this.m};d.prototype.setFragment=function(b){this.m=b?encodeURIComponent(b):null;return this};d.prototype.setRawFragment=function(b){this.m=b?b:null;return this};d.prototype.hasFragment=function(){return null!==this.m};var n=/^(?:([^:/?#]+):)?(?:\/\/(?:([^/?#]*)@)?([^/?#:@]*)(?::([0-9]+))?)?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,g=/[#\/\?@]/g,J=/[\#\?]/g;d.parse=b;
d.create=a;d.resolve=E;d.collapse_dots=f;d.utils={mimeTypeOf:function(a){var d=b(a);return/\.html$/.test(d.getPath())?"text/html":"application/javascript"},resolve:function(a,d){return a?E(b(a),b(d)).toString():""+d}};return d}(),S={atype:{NONE:0,URI:1,URI_FRAGMENT:11,SCRIPT:2,STYLE:3,HTML:12,ID:4,IDREF:5,IDREFS:6,GLOBAL_NAME:7,LOCAL_NAME:8,CLASSES:9,FRAME_TARGET:10,MEDIA_QUERY:13}};S.atype=S.atype;
S.ATTRIBS={"*::class":9,"*::dir":0,"*::draggable":0,"*::hidden":0,"*::id":4,"*::inert":0,"*::itemprop":0,"*::itemref":6,"*::itemscope":0,"*::lang":0,"*::onblur":2,"*::onchange":2,"*::onclick":2,"*::ondblclick":2,"*::onerror":2,"*::onfocus":2,"*::onkeydown":2,"*::onkeypress":2,"*::onkeyup":2,"*::onload":2,"*::onmousedown":2,"*::onmousemove":2,"*::onmouseout":2,"*::onmouseover":2,"*::onmouseup":2,"*::onreset":2,"*::onscroll":2,"*::onselect":2,"*::onsubmit":2,"*::ontouchcancel":2,"*::ontouchend":2,"*::ontouchenter":2,
"*::ontouchleave":2,"*::ontouchmove":2,"*::ontouchstart":2,"*::onunload":2,"*::spellcheck":0,"*::style":3,"*::tabindex":0,"*::title":0,"*::translate":0,"a::accesskey":0,"a::coords":0,"a::href":1,"a::hreflang":0,"a::name":7,"a::onblur":2,"a::onfocus":2,"a::shape":0,"a::target":10,"a::type":0,"area::accesskey":0,"area::alt":0,"area::coords":0,"area::href":1,"area::nohref":0,"area::onblur":2,"area::onfocus":2,"area::shape":0,"area::target":10,"audio::controls":0,"audio::loop":0,"audio::mediagroup":5,
"audio::muted":0,"audio::preload":0,"audio::src":1,"bdo::dir":0,"blockquote::cite":1,"br::clear":0,"button::accesskey":0,"button::disabled":0,"button::name":8,"button::onblur":2,"button::onfocus":2,"button::type":0,"button::value":0,"canvas::height":0,"canvas::width":0,"caption::align":0,"col::align":0,"col::char":0,"col::charoff":0,"col::span":0,"col::valign":0,"col::width":0,"colgroup::align":0,"colgroup::char":0,"colgroup::charoff":0,"colgroup::span":0,"colgroup::valign":0,"colgroup::width":0,
"command::checked":0,"command::command":5,"command::disabled":0,"command::icon":1,"command::label":0,"command::radiogroup":0,"command::type":0,"data::value":0,"del::cite":1,"del::datetime":0,"details::open":0,"dir::compact":0,"div::align":0,"dl::compact":0,"fieldset::disabled":0,"font::color":0,"font::face":0,"font::size":0,"form::accept":0,"form::action":1,"form::autocomplete":0,"form::enctype":0,"form::method":0,"form::name":7,"form::novalidate":0,"form::onreset":2,"form::onsubmit":2,"form::target":10,
"h1::align":0,"h2::align":0,"h3::align":0,"h4::align":0,"h5::align":0,"h6::align":0,"hr::align":0,"hr::noshade":0,"hr::size":0,"hr::width":0,"iframe::align":0,"iframe::frameborder":0,"iframe::height":0,"iframe::marginheight":0,"iframe::marginwidth":0,"iframe::width":0,"img::align":0,"img::alt":0,"img::border":0,"img::height":0,"img::hspace":0,"img::ismap":0,"img::name":7,"img::src":1,"img::usemap":11,"img::vspace":0,"img::width":0,"input::accept":0,"input::accesskey":0,"input::align":0,"input::alt":0,
"input::autocomplete":0,"input::checked":0,"input::disabled":0,"input::inputmode":0,"input::ismap":0,"input::list":5,"input::max":0,"input::maxlength":0,"input::min":0,"input::multiple":0,"input::name":8,"input::onblur":2,"input::onchange":2,"input::onfocus":2,"input::onselect":2,"input::pattern":0,"input::placeholder":0,"input::readonly":0,"input::required":0,"input::size":0,"input::src":1,"input::step":0,"input::type":0,"input::usemap":11,"input::value":0,"ins::cite":1,"ins::datetime":0,"label::accesskey":0,
"label::for":5,"label::onblur":2,"label::onfocus":2,"legend::accesskey":0,"legend::align":0,"li::type":0,"li::value":0,"map::name":7,"menu::compact":0,"menu::label":0,"menu::type":0,"meter::high":0,"meter::low":0,"meter::max":0,"meter::min":0,"meter::optimum":0,"meter::value":0,"ol::compact":0,"ol::reversed":0,"ol::start":0,"ol::type":0,"optgroup::disabled":0,"optgroup::label":0,"option::disabled":0,"option::label":0,"option::selected":0,"option::value":0,"output::for":6,"output::name":8,"p::align":0,
"pre::width":0,"progress::max":0,"progress::min":0,"progress::value":0,"q::cite":1,"select::autocomplete":0,"select::disabled":0,"select::multiple":0,"select::name":8,"select::onblur":2,"select::onchange":2,"select::onfocus":2,"select::required":0,"select::size":0,"source::type":0,"table::align":0,"table::bgcolor":0,"table::border":0,"table::cellpadding":0,"table::cellspacing":0,"table::frame":0,"table::rules":0,"table::summary":0,"table::width":0,"tbody::align":0,"tbody::char":0,"tbody::charoff":0,
"tbody::valign":0,"td::abbr":0,"td::align":0,"td::axis":0,"td::bgcolor":0,"td::char":0,"td::charoff":0,"td::colspan":0,"td::headers":6,"td::height":0,"td::nowrap":0,"td::rowspan":0,"td::scope":0,"td::valign":0,"td::width":0,"textarea::accesskey":0,"textarea::autocomplete":0,"textarea::cols":0,"textarea::disabled":0,"textarea::inputmode":0,"textarea::name":8,"textarea::onblur":2,"textarea::onchange":2,"textarea::onfocus":2,"textarea::onselect":2,"textarea::placeholder":0,"textarea::readonly":0,"textarea::required":0,
"textarea::rows":0,"textarea::wrap":0,"tfoot::align":0,"tfoot::char":0,"tfoot::charoff":0,"tfoot::valign":0,"th::abbr":0,"th::align":0,"th::axis":0,"th::bgcolor":0,"th::char":0,"th::charoff":0,"th::colspan":0,"th::headers":6,"th::height":0,"th::nowrap":0,"th::rowspan":0,"th::scope":0,"th::valign":0,"th::width":0,"thead::align":0,"thead::char":0,"thead::charoff":0,"thead::valign":0,"tr::align":0,"tr::bgcolor":0,"tr::char":0,"tr::charoff":0,"tr::valign":0,"track::default":0,"track::kind":0,"track::label":0,
"track::srclang":0,"ul::compact":0,"ul::type":0,"video::controls":0,"video::height":0,"video::loop":0,"video::mediagroup":5,"video::muted":0,"video::poster":1,"video::preload":0,"video::src":1,"video::width":0};S.ATTRIBS=S.ATTRIBS;S.eflags={OPTIONAL_ENDTAG:1,EMPTY:2,CDATA:4,RCDATA:8,UNSAFE:16,FOLDABLE:32,SCRIPT:64,STYLE:128,VIRTUALIZED:256};S.eflags=S.eflags;
S.ELEMENTS={a:0,abbr:0,acronym:0,address:0,applet:272,area:2,article:0,aside:0,audio:0,b:0,base:274,basefont:274,bdi:0,bdo:0,big:0,blockquote:0,body:305,br:2,button:0,canvas:0,caption:0,center:0,cite:0,code:0,col:2,colgroup:1,command:2,data:0,datalist:0,dd:1,del:0,details:0,dfn:0,dialog:272,dir:0,div:0,dl:0,dt:1,em:0,fieldset:0,figcaption:0,figure:0,font:0,footer:0,form:0,frame:274,frameset:272,h1:0,h2:0,h3:0,h4:0,h5:0,h6:0,head:305,header:0,hgroup:0,hr:2,html:305,i:0,iframe:4,img:2,input:2,ins:0,
isindex:274,kbd:0,keygen:274,label:0,legend:0,li:1,link:274,map:0,mark:0,menu:0,meta:274,meter:0,nav:0,nobr:0,noembed:276,noframes:276,noscript:276,object:272,ol:0,optgroup:0,option:1,output:0,p:1,param:274,pre:0,progress:0,q:0,s:0,samp:0,script:84,section:0,select:0,small:0,source:2,span:0,strike:0,strong:0,style:148,sub:0,summary:0,sup:0,table:0,tbody:1,td:1,textarea:8,tfoot:1,th:1,thead:1,time:0,title:280,tr:1,track:2,tt:0,u:0,ul:0,"var":0,video:0,wbr:2};S.ELEMENTS=S.ELEMENTS;
S.ELEMENT_DOM_INTERFACES={a:"HTMLAnchorElement",abbr:"HTMLElement",acronym:"HTMLElement",address:"HTMLElement",applet:"HTMLAppletElement",area:"HTMLAreaElement",article:"HTMLElement",aside:"HTMLElement",audio:"HTMLAudioElement",b:"HTMLElement",base:"HTMLBaseElement",basefont:"HTMLBaseFontElement",bdi:"HTMLElement",bdo:"HTMLElement",big:"HTMLElement",blockquote:"HTMLQuoteElement",body:"HTMLBodyElement",br:"HTMLBRElement",button:"HTMLButtonElement",canvas:"HTMLCanvasElement",caption:"HTMLTableCaptionElement",
center:"HTMLElement",cite:"HTMLElement",code:"HTMLElement",col:"HTMLTableColElement",colgroup:"HTMLTableColElement",command:"HTMLCommandElement",data:"HTMLElement",datalist:"HTMLDataListElement",dd:"HTMLElement",del:"HTMLModElement",details:"HTMLDetailsElement",dfn:"HTMLElement",dialog:"HTMLDialogElement",dir:"HTMLDirectoryElement",div:"HTMLDivElement",dl:"HTMLDListElement",dt:"HTMLElement",em:"HTMLElement",fieldset:"HTMLFieldSetElement",figcaption:"HTMLElement",figure:"HTMLElement",font:"HTMLFontElement",
footer:"HTMLElement",form:"HTMLFormElement",frame:"HTMLFrameElement",frameset:"HTMLFrameSetElement",h1:"HTMLHeadingElement",h2:"HTMLHeadingElement",h3:"HTMLHeadingElement",h4:"HTMLHeadingElement",h5:"HTMLHeadingElement",h6:"HTMLHeadingElement",head:"HTMLHeadElement",header:"HTMLElement",hgroup:"HTMLElement",hr:"HTMLHRElement",html:"HTMLHtmlElement",i:"HTMLElement",iframe:"HTMLIFrameElement",img:"HTMLImageElement",input:"HTMLInputElement",ins:"HTMLModElement",isindex:"HTMLUnknownElement",kbd:"HTMLElement",
keygen:"HTMLKeygenElement",label:"HTMLLabelElement",legend:"HTMLLegendElement",li:"HTMLLIElement",link:"HTMLLinkElement",map:"HTMLMapElement",mark:"HTMLElement",menu:"HTMLMenuElement",meta:"HTMLMetaElement",meter:"HTMLMeterElement",nav:"HTMLElement",nobr:"HTMLElement",noembed:"HTMLElement",noframes:"HTMLElement",noscript:"HTMLElement",object:"HTMLObjectElement",ol:"HTMLOListElement",optgroup:"HTMLOptGroupElement",option:"HTMLOptionElement",output:"HTMLOutputElement",p:"HTMLParagraphElement",param:"HTMLParamElement",
pre:"HTMLPreElement",progress:"HTMLProgressElement",q:"HTMLQuoteElement",s:"HTMLElement",samp:"HTMLElement",script:"HTMLScriptElement",section:"HTMLElement",select:"HTMLSelectElement",small:"HTMLElement",source:"HTMLSourceElement",span:"HTMLSpanElement",strike:"HTMLElement",strong:"HTMLElement",style:"HTMLStyleElement",sub:"HTMLElement",summary:"HTMLElement",sup:"HTMLElement",table:"HTMLTableElement",tbody:"HTMLTableSectionElement",td:"HTMLTableDataCellElement",textarea:"HTMLTextAreaElement",tfoot:"HTMLTableSectionElement",
th:"HTMLTableHeaderCellElement",thead:"HTMLTableSectionElement",time:"HTMLTimeElement",title:"HTMLTitleElement",tr:"HTMLTableRowElement",track:"HTMLTrackElement",tt:"HTMLElement",u:"HTMLElement",ul:"HTMLUListElement","var":"HTMLElement",video:"HTMLVideoElement",wbr:"HTMLElement"};S.ELEMENT_DOM_INTERFACES=S.ELEMENT_DOM_INTERFACES;S.ueffects={NOT_LOADED:0,SAME_DOCUMENT:1,NEW_DOCUMENT:2};S.ueffects=S.ueffects;
S.URIEFFECTS={"a::href":2,"area::href":2,"audio::src":1,"blockquote::cite":0,"command::icon":1,"del::cite":0,"form::action":2,"img::src":1,"input::src":1,"ins::cite":0,"q::cite":0,"video::poster":1,"video::src":1};S.URIEFFECTS=S.URIEFFECTS;S.ltypes={UNSANDBOXED:2,SANDBOXED:1,DATA:0};S.ltypes=S.ltypes;
S.LOADERTYPES={"a::href":2,"area::href":2,"audio::src":2,"blockquote::cite":2,"command::icon":1,"del::cite":2,"form::action":2,"img::src":1,"input::src":1,"ins::cite":2,"q::cite":2,"video::poster":1,"video::src":2};S.LOADERTYPES=S.LOADERTYPES;
var xa=function(b){function a(b){if(X.hasOwnProperty(b))return X[b];var a=b.match(oa);return a?String.fromCharCode(parseInt(a[1],10)):(a=b.match(pa))?String.fromCharCode(parseInt(a[1],16)):Y&&qa.test(b)?(Y.innerHTML="&"+b+";",a=Y.textContent,X[b]=a):"&"+b+";"}function c(b,d){return a(d)}function e(b){return b.replace(P,"")}function h(b){return b.replace(N,c)}function l(b){return(""+b).replace(k,"&amp;").replace(C,"&lt;").replace(x,"&gt;").replace(Q,"&#34;")}function f(b){return b.replace(p,"&amp;$1").replace(C,
"&lt;").replace(x,"&gt;")}function E(b){var a={cdata:b.cdata||b.cdata,comment:b.comment||b.comment,endDoc:b.endDoc||b.endDoc,endTag:b.endTag||b.endTag,pcdata:b.pcdata||b.pcdata,rcdata:b.rcdata||b.rcdata,startDoc:b.startDoc||b.startDoc,startTag:b.startTag||b.startTag};return function(b,d){var Da=a,c=z(b);r(Da,c,0,{noMoreGT:!1,noMoreEndComments:!1},d)}}function d(b,a,d,c,m){return function(){r(b,a,d,c,m)}}function r(a,c,ra,u,m){try{a.startDoc&&0==ra&&a.startDoc(m);for(var e,t,f,q=ra,h=c.length;q<h;){var g=
c[q++],k=c[q];switch(g){case "&":U.test(k)?(a.pcdata&&a.pcdata("&"+k,m,D,d(a,c,q,u,m)),q++):a.pcdata&&a.pcdata("&amp;",m,D,d(a,c,q,u,m));break;case "</":(e=/^([-\w:]+)[^\'\"]*/.exec(k))?e[0].length===k.length&&">"===c[q+1]?(q+=2,f=e[1].toLowerCase(),a.endTag&&a.endTag(f,m,D,d(a,c,q,u,m))):q=F(c,q,a,m,D,u):a.pcdata&&a.pcdata("&lt;/",m,D,d(a,c,q,u,m));break;case "<":if(e=/^([-\w:]+)\s*\/?/.exec(k))if(e[0].length===k.length&&">"===c[q+1]){q+=2;f=e[1].toLowerCase();a.startTag&&a.startTag(f,[],m,D,d(a,
c,q,u,m));var p=b.ELEMENTS[f];p&sa&&(q=n(c,{name:f,next:q,eflags:p},a,m,D,u))}else q=v(c,q,a,m,D,u);else a.pcdata&&a.pcdata("&lt;",m,D,d(a,c,q,u,m));break;case "\x3c!--":if(!u.noMoreEndComments){for(t=q+1;t<h&&(">"!==c[t]||!/--$/.test(c[t-1]));t++);if(t<h){if(a.comment){var l=c.slice(q,t).join("");a.comment(l.substr(0,l.length-2),m,D,d(a,c,t+1,u,m))}q=t+1}else u.noMoreEndComments=!0}u.noMoreEndComments&&a.pcdata&&a.pcdata("&lt;!--",m,D,d(a,c,q,u,m));break;case "<!":if(/^\w/.test(k)){if(!u.noMoreGT){for(t=
q+1;t<h&&">"!==c[t];t++);t<h?q=t+1:u.noMoreGT=!0}u.noMoreGT&&a.pcdata&&a.pcdata("&lt;!",m,D,d(a,c,q,u,m))}else a.pcdata&&a.pcdata("&lt;!",m,D,d(a,c,q,u,m));break;case "<?":if(!u.noMoreGT){for(t=q+1;t<h&&">"!==c[t];t++);t<h?q=t+1:u.noMoreGT=!0}u.noMoreGT&&a.pcdata&&a.pcdata("&lt;?",m,D,d(a,c,q,u,m));break;case ">":a.pcdata&&a.pcdata("&gt;",m,D,d(a,c,q,u,m));break;case "":break;default:a.pcdata&&a.pcdata(g,m,D,d(a,c,q,u,m))}}a.endDoc&&a.endDoc(m)}catch(x){if(x!==D)throw x;}}function z(b){var a=/(<\/|<\!--|<[!?]|[&<>])/g;
b+="";if(ja)return b.split(a);for(var c=[],d=0,m;null!==(m=a.exec(b));)c.push(b.substring(d,m.index)),c.push(m[0]),d=m.index+m[0].length;c.push(b.substring(d));return c}function F(b,a,c,e,m,f){var t=g(b,a);if(!t)return b.length;c.endTag&&c.endTag(t.name,e,m,d(c,b,a,f,e));return t.next}function v(b,a,c,e,m,f){a=g(b,a);if(!a)return b.length;c.startTag&&c.startTag(a.name,a.attrs,e,m,d(c,b,a.next,f,e));return a.eflags&sa?n(b,a,c,e,m,f):a.next}function n(a,c,e,u,m,h){var t=a.length;ka.hasOwnProperty(c.name)||
(ka[c.name]=new RegExp("^"+c.name+"(?:[\\s\\/]|$)","i"));for(var k=ka[c.name],q=c.next,g=c.next+1;g<t&&("</"!==a[g-1]||!k.test(a[g]));g++);g<t&&--g;var p=a.slice(q,g).join("");if(c.eflags&b.eflags.CDATA)e.cdata&&e.cdata(p,u,m,d(e,a,g,h,u));else if(c.eflags&b.eflags.RCDATA)e.rcdata&&e.rcdata(f(p),u,m,d(e,a,g,h,u));else throw Error("bug");return g}function g(a,c){var d=/^([-\w:]+)/.exec(a[c]),e={};e.name=d[1].toLowerCase();e.eflags=b.ELEMENTS[e.name];var m=a[c].substr(d[0].length);c+=1;for(var f=a.length;c<
f&&">"!==a[c];c++)m+=a[c];if(!(f<=c)){for(var t=[];""!==m;)if(d=H.exec(m))if(d[4]&&!d[5]||d[6]&&!d[7]){for(var h=d[4]||d[6],g=!1,k=[m,a[c++]];c<f;c++){if(g){if(">"===a[c])break}else 0<=a[c].indexOf(h)&&(g=!0);k.push(a[c])}if(f<=c)break;m=k.join("")}else{var p=d[1].toLowerCase(),l=d[2]?J(d[3]):"";t.push(p,l);m=m.substr(d[0].length)}else m=m.replace(/^[\s\S][^a-z\s]*/,"");e.attrs=t;e.next=c+1;return e}}function J(b){var a=b.charCodeAt(0);if(34===a||39===a)b=b.substr(1,b.length-2);return h(e(b))}function G(a){function c(b,
a){e||a.push(b)}var d,e;return E({startDoc:function(){d=[];e=!1},startTag:function(c,f,h){if(!e&&b.ELEMENTS.hasOwnProperty(c)){var g=b.ELEMENTS[c];if(!(g&b.eflags.FOLDABLE)){var k=a(c,f);if(k){if("object"!==typeof k)throw Error("tagPolicy did not return object (old API?)");if("attribs"in k)f=k.attribs;else throw Error("tagPolicy gave no attribs");var p,x;"tagName"in k?(x=k.tagName,p=b.ELEMENTS[x]):(x=c,p=g);if(g&b.eflags.OPTIONAL_ENDTAG){var K=d[d.length-1];!K||K.orig!==c||K.rep===x&&c===x||h.push("</",
K.rep,">")}g&b.eflags.EMPTY||d.push({orig:c,rep:x});h.push("<",x);for(var C=0,n=f.length;C<n;C+=2){var H=f[C],ia=f[C+1];null!==ia&&void 0!==ia&&h.push(" ",H,'="',l(ia),'"')}h.push(">");g&b.eflags.EMPTY&&!(p&b.eflags.EMPTY)&&h.push("</",x,">")}else e=!(g&b.eflags.EMPTY)}}},endTag:function(a,c){if(e)e=!1;else if(b.ELEMENTS.hasOwnProperty(a)){var f=b.ELEMENTS[a];if(!(f&(b.eflags.EMPTY|b.eflags.FOLDABLE))){if(f&b.eflags.OPTIONAL_ENDTAG)for(f=d.length;0<=--f;){var h=d[f].orig;if(h===a)break;if(!(b.ELEMENTS[h]&
b.eflags.OPTIONAL_ENDTAG))return}else for(f=d.length;0<=--f&&d[f].orig!==a;);if(!(0>f)){for(var g=d.length;--g>f;){var k=d[g].rep;b.ELEMENTS[k]&b.eflags.OPTIONAL_ENDTAG||c.push("</",k,">")}f<d.length&&(a=d[f].rep);d.length=f;c.push("</",a,">")}}}},pcdata:c,rcdata:c,cdata:c,endDoc:function(b){for(;d.length;d.length--)b.push("</",d[d.length-1].rep,">")}})}function O(b,a,c,d,e){if(!e)return null;try{var f=wa.parse(""+b);if(f&&(!f.hasScheme()||Ea.test(f.getScheme()))){var h=e(f,a,c,d);return h?h.toString():
null}}catch(g){}return null}function y(b,a,c,d,e){c||b(a+" removed",{change:"removed",tagName:a});if(d!==e){var f="changed";d&&!e?f="removed":!d&&e&&(f="added");b(a+"."+c+" "+f,{change:f,tagName:a,attribName:c,oldValue:d,newValue:e})}}function T(b,a,c){var d;d=a+"::"+c;if(b.hasOwnProperty(d))return b[d];d="*::"+c;if(b.hasOwnProperty(d))return b[d]}function na(a,c){return T(b.ATTRIBS,a,c)}function M(a,c){return T(b.LOADERTYPES,a,c)}function V(a,c){return T(b.URIEFFECTS,a,c)}function W(a,c,d,e,f){for(var h=
0;h<c.length;h+=2){var g=c[h],k=c[h+1],p=k,x=null,l;if((l=a+"::"+g,b.ATTRIBS.hasOwnProperty(l))||(l="*::"+g,b.ATTRIBS.hasOwnProperty(l)))x=b.ATTRIBS[l];if(null!==x)switch(x){case b.atype.NONE:break;case b.atype.SCRIPT:k=null;f&&y(f,a,g,p,k);break;case b.atype.STYLE:if("undefined"===typeof Z){k=null;f&&y(f,a,g,p,k);break}var K=[];Z(k,{declaration:function(a,c){var f=a.toLowerCase();aa(f,c,d?function(a){return O(a,b.ueffects.SAME_DOCUMENT,b.ltypes.SANDBOXED,{TYPE:"CSS",CSS_PROP:f},d)}:null);c.length&&
K.push(f+": "+c.join(" "))}});k=0<K.length?K.join(" ; "):null;f&&y(f,a,g,p,k);break;case b.atype.ID:case b.atype.IDREF:case b.atype.IDREFS:case b.atype.GLOBAL_NAME:case b.atype.LOCAL_NAME:case b.atype.CLASSES:k=e?e(k):k;f&&y(f,a,g,p,k);break;case b.atype.URI:k=O(k,V(a,g),M(a,g),{TYPE:"MARKUP",XML_ATTR:g,XML_TAG:a},d);f&&y(f,a,g,p,k);break;case b.atype.URI_FRAGMENT:k&&"#"===k.charAt(0)?(k=k.substring(1),k=e?e(k):k,null!==k&&void 0!==k&&(k="#"+k)):k=null;f&&y(f,a,g,p,k);break;default:k=null,f&&y(f,
a,g,p,k)}else k=null,f&&y(f,a,g,p,k);c[h+1]=k}return c}function ba(a,c,d){return function(f,e){if(b.ELEMENTS[f]&b.eflags.UNSAFE)d&&y(d,f,void 0,void 0,void 0);else return{attribs:W(f,e,a,c,d)}}}function R(b,a){var c=[];G(a)(b,c);return c.join("")}function K(b,a,c,d){a=ba(a,c,d);return R(b,a)}var Z,aa,ta;"undefined"!==typeof window&&(Z=window.parseCssDeclarations,aa=window.sanitizeCssProperty,ta=window.cssSchema);var X={lt:"<",LT:"<",gt:">",GT:">",amp:"&",AMP:"&",quot:'"',apos:"'",nbsp:"\u00a0"},oa=
/^#(\d+)$/,pa=/^#x([0-9A-Fa-f]+)$/,qa=/^[A-Za-z][A-za-z0-9]+$/,Y="undefined"!==typeof window&&window.document?window.document.createElement("textarea"):null,P=/\0/g,N=/&(#[0-9]+|#[xX][0-9A-Fa-f]+|\w+);/g,U=/^(#[0-9]+|#[xX][0-9A-Fa-f]+|\w+);/,k=/&/g,p=/&([^a-z#]|#(?:[^0-9x]|x(?:[^0-9a-f]|$)|$)|$)/gi,C=/[<]/g,x=/>/g,Q=/\"/g,H=/^\s*([-.:\w]+)(?:\s*(=)\s*((")[^"]*("|$)|(')[^']*('|$)|(?=[a-z][-\w]*\s*=)|[^"'\s]*))?/i,ja=3==="a,b".split(/(,)/).length,sa=b.eflags.CDATA|b.eflags.RCDATA,D={},ka={},Ea=/^(?:https?|mailto)$/i,
A={};A.escapeAttrib=A.escapeAttrib=l;A.makeHtmlSanitizer=A.makeHtmlSanitizer=G;A.makeSaxParser=A.makeSaxParser=E;A.makeTagPolicy=A.makeTagPolicy=ba;A.normalizeRCData=A.normalizeRCData=f;A.sanitize=A.sanitize=K;A.sanitizeAttribs=A.sanitizeAttribs=W;A.sanitizeWithPolicy=A.sanitizeWithPolicy=R;A.unescapeEntities=A.unescapeEntities=h;return A}(S);var ya={applet:!0,audio:!0,base:!0,embed:!0,form:!0,frame:!0,frameset:!0,iframe:!0,img:!0,input:!0,link:!0,meta:!0,object:!0,script:!0,style:!0,svg:!0,template:!0,textarea:!0,video:!0},za={br:!0,col:!0,hr:!0,img:!0,source:!0,track:!0,wbr:!0},Aa="b br code del em i ins mark q s small strong sub sup time u".split(" "),Ba=["fallback","href","on","placeholder"],Ca=["javascript:","vbscript:","data:","<script","\x3c/script"];
function Fa(b){function a(b){0==h&&e.push(b)}var c=xa.makeTagPolicy(),e=[],h=0,l=xa.makeSaxParser({startTag:function(b,e){if(0<h)za[b]||h++;else{if(ya[b])h++;else if(0!=b.indexOf("amp-")){var d=e.slice(0),l=c(b,e);if(l){e=l.attribs;for(var z=0;z<e.length;z+=2)-1!=Ba.indexOf(e[z])&&(e[z+1]=d[z+1])}else h++}if(0<h)za[b]&&h--;else{a("<");a(b);for(z=0;z<e.length;z+=2){var F=e[z],v=e[z+1],n;a:{n=F;var g=v;if(0==n.indexOf("on")&&"on"!=n||"style"==n)n=!1;else{if(g)for(n=g.toLowerCase().replace(/[\s,\u0000]+/g,
""),g=0;g<Ca.length;g++)if(-1!=n.indexOf(Ca[g])){n=!1;break a}n=!0}}n&&(a(" "),a(F),a('="'),v&&a(xa.escapeAttrib(Ga(b,F,v))),a('"'))}a(">")}}},endTag:function(b){0<h?h--:(a("</"),a(b),a(">"))},pcdata:a,rcdata:a,cdata:a});l(b);return e.join("")}function Ga(b,a,c){return"src"==a||"href"==a||"srcset"==a?Ha(b,a,c):c}
function Ha(b,a,c){var e=self.location;var h=I(c).search,l=Object.create(null);if(h){if(0==h.indexOf("?")||0==h.indexOf("#"))h=h.substr(1);for(var h=h.split("&"),f=0;f<h.length;f++){var E=h[f],d=E.indexOf("="),r;-1!=d?(r=decodeURIComponent(E.substring(0,d)).trim(),E=decodeURIComponent(E.substring(d+1)).trim()):(r=decodeURIComponent(E).trim(),E="");r&&(l[r]=E)}}w().assert(!("__amp_source_origin"in l),"Source origin is not allowed in %s",c);var z=ha(e);l=e;"string"==typeof l&&(l=I(l));ha(l)?(h=l.pathname.split("/"),
f=h[1],w().assert("c"==f||"v"==f,"Unknown path prefix in url %s",l.href),f=h[2],r="s"==f?"https://"+decodeURIComponent(h[3]):"http://"+decodeURIComponent(f),w().assert(0<r.indexOf("."),"Expected a . in origin %s",r),h.splice(1,"s"==f?3:2),h=r+h.join("/"),f=(f=l.search)&&"?"!=f?(f=f.replace(ga,"").replace(/^[?&]/,""))?"?"+f:"":"",l=h+f+(l.hash||"")):l=l.href;l=I(l);if("href"==a&&0!=c.indexOf("#"))return la(c,l);if("src"==a)return"amp-img"==b?Ia(c,l,z):la(c,l);if("srcset"==a){var F;try{var v=c.match(/\s*(?:[\S]*)(?:\s+(?:-?(?:\d+(?:\.(?:\d+)?)?|\.\d+)[a-zA-Z]))?(?:\s*,)?/g);
w().assert(0<v.length,"srcset has to have at least one source: %s",void 0);b=[];for(a=0;a<v.length;a++){var n=v[a].trim();","==n.substr(-1)&&(n=n.substr(0,n.length-1).trim());var g=n.split(/\s+/,2);if(0!=g.length&&(1!=g.length||g[0])&&(2!=g.length||g[0]||g[1])){var J=g[0];if(1==g.length||2==g.length&&!g[1])b.push({url:J,width:void 0,dpr:1});else{var G=g[1].toLowerCase(),O=G.substring(G.length-1);"w"==O?b.push({url:J,width:parseFloat(G),dpr:void 0}):"x"==O&&b.push({url:J,width:void 0,dpr:parseFloat(G)})}}}F=
new L(b)}catch(y){return w().error("sanitizer","Failed to parse srcset: ",y),c}c=F.getSources();for(v=0;v<c.length;v++)c[v].url=Ia(c[v].url,l,z);return F.stringify()}return c}function Ia(b,a,c){b=I(la(b,a));return"data:"==b.protocol||ha(b)||!c?b.href:ea+"/i/"+("https:"==b.protocol?"s/":"")+encodeURIComponent(b.host)+b.pathname+(b.search||"")+(b.hash||"")};var Ja={};
(function defineMustache(a,c){c(Ja)})(this,function mustacheFactory(a){function c(a){return"function"===typeof a}function e(a){return G(a)?"array":typeof a}function h(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&")}function l(a,c){return null!=a&&"object"===typeof a&&Object.prototype.hasOwnProperty.call(a,c)}function f(a,c){return O.call(a,c)}function E(a){return!f(y,a)}function d(a){return String(a).replace(/[&<>"'`=\/]/g,function aa(a){return T[a]})}function r(c,d){function e(){if(r&&!y)for(;n.length;)delete l[n.pop()];
else n=[];y=r=!1}function f(a){"string"===typeof a&&(a=a.split(M,2));if(!G(a)||2!==a.length)throw Error("Invalid tags: "+a);P=new RegExp(h(a[0])+"\\s*");N=new RegExp("\\s*"+h(a[1]));U=new RegExp("\\s*"+h("}"+a[1]))}if(!c)return[];var g=[],l=[],n=[],r=!1,y=!1,P,N,U;f(d||a.tags);for(var k=new v(c),p,C,x,Q,H;!k.eos();){c=k.pos;if(C=k.scanUntil(P)){p=0;for(var ja=C.length;p<ja;++p)x=C.charAt(p),E(x)?n.push(l.length):y=!0,l.push(["text",x,c,c+1]),c+=1,"\n"===x&&e()}if(!k.scan(P))break;r=!0;p=k.scan(ba)||
"name";k.scan(na);"="===p?(C=k.scanUntil(V),k.scan(V),k.scanUntil(N)):"{"===p?(C=k.scanUntil(U),k.scan(W),k.scanUntil(N),p="&"):C=k.scanUntil(N);if(!k.scan(N))throw Error("Unclosed tag at "+k.pos);Q=[p,C,c,k.pos];l.push(Q);if("#"===p||"^"===p)g.push(Q);else if("/"===p){H=g.pop();if(!H)throw Error('Unopened section "'+C+'" at '+c);if(H[1]!==C)throw Error('Unclosed section "'+H[1]+'" at '+c);}else if("name"===p||"{"===p||"&"===p)y=!0}if(H=g.pop())throw Error('Unclosed section "'+H[1]+'" at '+k.pos);
return F(z(l))}function z(a){for(var c=[],d,e,f=0,g=a.length;f<g;++f)if(d=a[f])"text"===d[0]&&e&&"text"===e[0]?(e[1]+=d[1],e[3]=d[3]):(c.push(d),e=d);return c}function F(a){for(var c=[],d=c,e=[],f,g,h=0,l=a.length;h<l;++h)switch(f=a[h],f[0]){case "#":case "^":d.push(f);e.push(f);d=f[4]=[];break;case "/":g=e.pop();g[5]=f[2];d=0<e.length?e[e.length-1][4]:c;break;default:d.push(f)}return c}function v(a){this.tail=this.string=a;this.pos=0}function n(a,c){this.view=a;this.cache={".":this.view};this.parent=
c}function g(){this.cache={}}var J=Object.prototype.toString,G=Array.isArray||function Z(a){return"[object Array]"===J.call(a)},O=RegExp.prototype.test,y=/\S/,T={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;","`":"&#x60;","=":"&#x3D;"},na=/\s*/,M=/\s+/,V=/\s*=/,W=/\s*\}/,ba=/#|\^|\/|>|\{|&|=|!/;v.prototype.eos=function aa(){return""===this.tail};v.prototype.scan=function ta(a){var c=this.tail.match(a);if(!c||0!==c.index)return"";a=c[0];this.tail=this.tail.substring(a.length);
this.pos+=a.length;return a};v.prototype.scanUntil=function X(a){a=this.tail.search(a);var c;switch(a){case -1:c=this.tail;this.tail="";break;case 0:c="";break;default:c=this.tail.substring(0,a),this.tail=this.tail.substring(a)}this.pos+=c.length;return c};n.prototype.push=function oa(a){return new n(a,this)};n.prototype.lookup=function pa(a){var d=this.cache,e;if(d.hasOwnProperty(a))e=d[a];else{for(var f=this,g,k,h=!1;f;){if(0<a.indexOf("."))for(e=f.view,g=a.split("."),k=0;null!=e&&k<g.length;){if(!l(e,
g[k])){e=null;break}k===g.length-1&&(h=!0);e=e[g[k++]]}else l(f.view,a)?(e=f.view[a],h=!0):e=null;if(h)break;f=f.parent}d[a]=e}c(e)&&(e=e.call(this.view));return e};g.prototype.clearCache=function qa(){this.cache={}};g.prototype.parse=function(a,c){var d=this.cache,e=d[a];null==e&&(e=d[a]=r(a,c));return e};g.prototype.render=function Y(a,c,d){var e=this.parse(a);c=c instanceof n?c:new n(c);return this.renderTokens(e,c,d,a)};g.prototype.renderTokens=function P(a,c,d,e){for(var f="",g,h,l,n=0,r=a.length;n<
r;++n)l=void 0,g=a[n],h=g[0],"#"===h?l=this.renderSection(g,c,d,e):"^"===h?l=this.renderInverted(g,c,d,e):">"===h?l=this.renderPartial(g,c,d,e):"&"===h?l=this.unescapedValue(g,c):"name"===h?l=this.escapedValue(g,c):"text"===h&&(l=this.rawValue(g)),void 0!==l&&(f+=l);return f};g.prototype.renderSection=function N(a,d,e,f){function g(a){return h.render(a,d,e)}var h=this,l="",n=d.lookup(a[1]);if(n){if(G(n))for(var r=0,v=n.length;r<v;++r)l+=this.renderTokens(a[4],d.push(n[r]),e,f);else if("object"===
typeof n||"string"===typeof n||"number"===typeof n)l+=this.renderTokens(a[4],d.push(n),e,f);else if(c(n)){if("string"!==typeof f)throw Error("Cannot use higher-order sections without the original template");n=n.call(d.view,f.slice(a[3],a[5]),g);null!=n&&(l+=n)}else l+=this.renderTokens(a[4],d,e,f);return l}};g.prototype.renderInverted=function U(a,c,d,e){var f=c.lookup(a[1]);if(!f||G(f)&&0===f.length)return this.renderTokens(a[4],c,d,e)};g.prototype.renderPartial=function k(a,d,e){if(e&&(a=c(e)?e(a[1]):
e[a[1]],null!=a))return this.renderTokens(this.parse(a),d,e,a)};g.prototype.unescapedValue=function p(c,d){c=d.lookup(c[1]);if(null!=c)return a.sanitizeUnescaped?a.sanitizeUnescaped(c):c};g.prototype.escapedValue=function C(c,d){c=d.lookup(c[1]);if(null!=c)return a.escape(c)};g.prototype.rawValue=function x(a){return a[1]};a.name="mustache.js";a.version="2.2.0";a.tags=["{{","}}"];var R=new g;a.clearCache=function(){return R.clearCache()};a.parse=function(a,c){return R.parse(a,c)};a.render=function(a,
c,d){if("string"!==typeof a)throw new TypeError('Invalid template! Template should be a "string" but "'+e(a)+'" was given as the first argument for mustache#render(template, view, partials)');return R.render(a,c,d)};a.to_html=function Q(d,e,f,g){var h=a.render(d,e,f);if(c(g))g(h);else return h};a.escape=d;a.sanitizeUnescaped=null;a.setUnescapedSanitizier=function H(c){a.sanitizeUnescaped=c};a.Scanner=v;a.Context=n;a.Writer=g});Ja.setUnescapedSanitizier(function(b){return xa.sanitizeWithPolicy(b,function(a){return-1==Aa.indexOf(a)?null:{tagName:a,attribs:[]}})});function Ka(b){AMP.BaseTemplate.apply(this,arguments)}ca(Ka,AMP.BaseTemplate);Ka.prototype.compileCallback=function(){this.A=this.element.innerHTML;Ja.parse(this.A)};Ka.prototype.render=function(b){b=Ja.render(this.A,b);var a=Fa(b);b=this.win.document.createElement("div");b.innerHTML=a;return this.unwrap(b)};AMP.registerTemplate("amp-mustache",Ka);
})});
//# sourceMappingURL=amp-mustache-0.1.js.map
