(window.AMP = window.AMP || []).push({n:"amp-ad", f:(function(AMP) {var process={env:{NODE_ENV:"production"}};var n;function p(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}var v="";
function w(){var a=void 0,b=a||self,c;if(b.AMP_MODE)c=b.AMP_MODE;else{c=b;if(c.context&&c.context.mode)c=c.context.mode;else{var d=location.originalHash||location.hash,e=Object.create(null);if(d){if(0==d.indexOf("?")||0==d.indexOf("#"))d=d.substr(1);for(var d=d.split("&"),f=0;f<d.length;f++){var g=d[f],k=g.indexOf("="),h;-1!=k?(h=decodeURIComponent(g.substring(0,k)).trim(),g=decodeURIComponent(g.substring(k+1)).trim()):(h=decodeURIComponent(g).trim(),g="");h&&(e[h]=g)}}v||(v=c.AMP_CONFIG&&c.AMP_CONFIG.v?
c.AMP_CONFIG.v:"1475106123549");c={localDev:!1,development:!("1"!=e.development&&!c.AMP_DEV_MODE),filter:e.filter,minified:!0,test:!1,log:e.log,version:v}}c=b.AMP_MODE=c}return c};(new Date).getTime();var z=self.log=self.log||{user:null,dev:null};function A(){if(z.user)return z.user;throw Error("failed to call initLogConstructor");}function B(){if(z.dev)return z.dev;throw Error("failed to call initLogConstructor");};function C(a,b){a=a.__AMP_TOP||a;var c=a.services&&a.services[b]&&a.services[b].obj;return c}function aa(a,b,c){a=a.__AMP_TOP||a;return D(a,a,b,c?c:void 0)}function ba(a,b){var c=ca(a);a=ca(c);a=a.isSingleDoc()?a.win:a;return D(a,c,"documentInfo",b)}function ca(a){return a.nodeType?aa((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}
function D(a,b,c,d,e){var f=F(a),g=f[c];g||(g=f[c]={obj:null,promise:null,resolve:null});g.obj||(g.obj=e?new e(b):d(b),g.resolve&&g.resolve(g.obj));return g.obj}function da(a,b){var c=ea(a,b);if(c)return c;a=F(a);var d,e=new Promise(function(a){d=a});a[b]={obj:null,promise:e,resolve:d};return e}function ea(a,b){if(a=F(a)[b]){if(b=a.promise)return b;if(a.obj)return a.promise=Promise.resolve(a.obj)}return null}function F(a){var b=a.services;b||(b=a.services={});return b};function fa(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function ga(a,b){fa(a.documentElement,function(){return!!a.body},b)}function ha(a){return new Promise(function(b){ga(a,b)})}function ia(a,b){for(var c=a;c;c=c.parentElement)if(b(c))return c;return null}
function ja(a){var b="amp-ad";if(a.closest)return a.closest(b);b=b.toUpperCase();return ia(a,function(a){return a.tagName==b})};function ka(a){var b="amp-user-notification";return la(a,"userNotificationManager",b).then(function(a){return A().assert(a,"Service %s was requested to be provided through %s, but %s is not loaded in the current page. To fix this problem load the JavaScript file for %s in this page.","userNotificationManager",b,b,b)})}
function la(a,b,c){var d=ea(a,b);return d?d:Promise.resolve().then(function(){return a.ampExtendedElements[c]?da(a,b):ha(a.document).then(function(){return a.ampExtendedElements[c]?da(a,b):null})})};var ma={_ping_:{renderStartImplemented:!0},a9:{prefetch:"https://c.amazon-adsystem.com/aax2/assoc.js"},accesstrade:{prefetch:"https://h.accesstrade.net/js/amp/amp.js"},adblade:{prefetch:"https://web.adblade.com/js/ads/async/show.js",preconnect:["https://staticd.cdn.adblade.com","https://static.adblade.com"]},adform:{},adgeneration:{prefetch:"https://i.socdm.com/sdk/js/adg-script-loader.js"},adition:{},adman:{},adreactor:{},adsense:{prefetch:"https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",
preconnect:"https://googleads.g.doubleclick.net",clientIdScope:"AMP_ECID_GOOGLE"},adsnative:{prefetch:"https://static.adsnative.com/static/js/render.v1.js",preconnect:"https://api.adsnative.com"},adspirit:{},adstir:{prefetch:"https://js.ad-stir.com/js/adstir_async.js",preconnect:"https://ad.ad-stir.com"},adtech:{prefetch:"https://s.aolcdn.com/os/ads/adsWrapper3.js",preconnect:["https://mads.at.atwola.com","https://aka-cdn.adtechus.com"]},aduptech:{prefetch:"https://s.d.adup-tech.com/jsapi"},amoad:{prefetch:["https://j.amoad.com/js/a.js",
"https://j.amoad.com/js/n.js"],preconnect:["https://d.amoad.com","https://i.amoad.com","https://m.amoad.com","https://v.amoad.com"]},appnexus:{prefetch:"https://acdn.adnxs.com/ast/ast.js",preconnect:"https://ib.adnxs.com"},atomx:{prefetch:"https://s.ato.mx/p.js"},caprofitx:{prefetch:["https://cdn.caprofitx.com/pfx.min.js","https://cdn.caprofitx.com/tags/amp/profitx_amp.js"],preconnect:"https://ad.caprofitx.adtdp.com"},chargeads:{},colombia:{prefetch:"https://static.clmbtech.com/ad/commons/js/colombia-amp.js"},
contentad:{},criteo:{prefetch:"https://static.criteo.net/js/ld/publishertag.js",preconnect:"https://cas.criteo.com"},dotandads:{prefetch:"https://amp.ad.dotandad.com/dotandadsAmp.js",preconnect:"https://bal.ad.dotandad.com"},doubleclick:{prefetch:["https://www.googletagservices.com/tag/js/gpt.js","https://securepubads.g.doubleclick.net/static/glade.js"],preconnect:["https://partner.googleadservices.com","https://tpc.googlesyndication.com"],clientIdScope:"AMP_ECID_GOOGLE",renderStartImplemented:!0},
eplanning:{prefetch:"https://us.img.e-planning.net/layers/epl-amp.js"},ezoic:{prefetch:["https://www.googletagservices.com/tag/js/gpt.js","https://g.ezoic.net/ezoic/ampad.js"]},flite:{},genieessp:{prefetch:"https://js.gsspcln.jp/l/amp.js"},gmossp:{prefetch:"https://cdn.gmossp-sp.jp/ads/amp.js"},imobile:{prefetch:"https://spamp.i-mobile.co.jp/script/amp.js",preconnect:"https://spad.i-mobile.co.jp"},improvedigital:{},industrybrains:{prefetch:"https://web.industrybrains.com/js/ads/async/show.js",preconnect:["https://staticd.cdn.industrybrains.com",
"https://static.industrybrains.com"]},inmobi:{prefetch:"https://cf.cdn.inmobi.com/ad/inmobi.secure.js",renderStartImplemented:!0},kargo:{},mads:{prefetch:"https://eu2.madsone.com/js/tags.js"},"mantis-display":{prefetch:"https://assets.mantisadnetwork.com/mantodea.min.js",preconnect:["https://mantodea.mantisadnetwork.com","https://res.cloudinary.com","https://resize.mantisadnetwork.com"]},"mantis-recommend":{prefetch:"https://assets.mantisadnetwork.com/recommend.min.js",preconnect:["https://mantodea.mantisadnetwork.com",
"https://resize.mantisadnetwork.com"]},mediaimpact:{prefetch:"https://ec-ns.sascdn.com/diff/251/divscripte/amp.js"},meg:{renderStartImplemented:!0},microad:{prefetch:"https://j.microad.net/js/camp.js",preconnect:["https://s-rtb.send.microad.jp","https://s-rtb.send.microadinc.com","https://cache.send.microad.jp","https://cache.send.microadinc.com","https://deb.send.microad.jp"]},mixpo:{prefetch:"https://cdn.mixpo.com/js/loader.js",preconnect:["https://player1.mixpo.com","https://player2.mixpo.com"]},
nativo:{prefetch:"https://s.ntv.io/serve/load.js"},nend:{prefetch:"https://js1.nend.net/js/amp.js",preconnect:["https://output.nend.net","https://img1.nend.net"]},openadstream:{},openx:{prefetch:"https://www.googletagservices.com/tag/js/gpt.js",preconnect:["https://partner.googleadservices.com","https://securepubads.g.doubleclick.net","https://tpc.googlesyndication.com"]},plista:{},pubmatic:{prefetch:"https://ads.pubmatic.com/AdServer/js/amp.js"},pubmine:{prefetch:"https://s.pubmine.com/showad.js"},
pulsepoint:{prefetch:"https://ads.contextweb.com/TagPublish/getjs.static.js",preconnect:"https://tag.contextweb.com"},revcontent:{prefetch:"https://labs-cdn.revcontent.com/build/amphtml/revcontent.amp.min.js",preconnect:["https://trends.revcontent.com","https://cdn.revcontent.com","https://img.revcontent.com"]},rubicon:{},sharethrough:{},smartadserver:{prefetch:"https://ec-ns.sascdn.com/diff/js/amp.v0.js",preconnect:"https://static.sascdn.com",renderStartImplemented:!0},sortable:{prefetch:"https://www.googletagservices.com/tag/js/gpt.js",
preconnect:["https://tags-cdn.deployads.com","https://partner.googleadservices.com","https://securepubads.g.doubleclick.net","https://tpc.googlesyndication.com"]},sovrn:{prefetch:"https://ap.lijit.com/www/sovrn_amp/sovrn_ads.js"},taboola:{},teads:{prefetch:"https://cdn.teads.tv/media/format/v3/teads-format.min.js",preconnect:["https://cdn2.teads.tv","https://a.teads.tv","https://t.teads.tv"]},triplelift:{},webediads:{},"weborama-display":{prefetch:["https://cstatic.weborama.fr/js/advertiserv2/adperf_launch_1.0.0_scrambled.js",
"https://cstatic.weborama.fr/js/advertiserv2/adperf_core_1.0.0_scrambled.js"]},widespace:{},yahoojp:{prefetch:["https://s.yimg.jp/images/listing/tool/yads/ydn/amp/amp.js","https://yads.c.yimg.jp/js/yads.js"],preconnect:"https://yads.yahoo.co.jp"},yieldbot:{prefetch:["https://cdn.yldbt.com/js/yieldbot.intent.amp.js","https://msg.yldbt.com/js/ybmsg.html"],preconnect:"https://i.yldbt.com"},yieldmo:{prefetch:"https://static.yieldmo.com/ym.amp1.js",preconnect:["https://s.yieldmo.com","https://ads.yieldmo.com"],
renderStartImplemented:!0},yieldone:{prefetch:"https://img.ak.impact-ad.jp/ic/pone/commonjs/yone-amp.js"},zergnet:{},zucks:{preconnect:["https://j.zucks.net.zimg.jp","https://sh.zucks.net","https://k.zucks.net","https://static.zucks.net.zimg.jp"]}};function G(a){return C(a,"timer")};function na(a){var b=ma[a.element.getAttribute("type")],c=b?b.clientIdScope:null,d=a.element.getAttribute("data-consent-notification-id");if(!c&&!d)return Promise.resolve();var e=la(a.win,"cid","amp-analytics").then(function(b){if(b){var e=Promise.resolve();return d&&(e=ka(a.win).then(function(a){return a.get(d)}),!c&&d)?e:b.get(c,e).catch(function(a){B().error("ad-cid",a)})}});return G(a.win).timeoutPromise(1E3,e,"cid timeout").catch(function(a){B().warn(a)})};function oa(a){return a.replace(/-([a-z])/g,function(a,c){return c.toUpperCase()})}function pa(a){var b=".localhost",c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};var H=self.AMP_CONFIG||{},qa=H.thirdPartyUrl||"https://3p.ampproject.net",ra=H.thirdPartyFrameHost||"ampproject.net",sa=H.cdnUrl||"https://cdn.ampproject.org";var I,J,ua=/[?&]amp_js[^&]*/;
function K(a){I||(I=self.document.createElement("a"),J=self.UrlCache||(self.UrlCache=Object.create(null)));var b=J[a];if(b)return b;I.href=a;I.protocol||(I.href=I.href);var c={href:I.href,protocol:I.protocol,host:I.host,hostname:I.hostname,port:"0"==I.port?"":I.port,pathname:I.pathname,search:I.search,hash:I.hash,origin:null};"/"!==c.pathname[0]&&(c.pathname="/"+c.pathname);if("http:"==c.protocol&&80==c.port||"https:"==c.protocol&&443==c.port)c.port="",c.host=c.hostname;c.origin=I.origin&&"null"!=
I.origin?I.origin:"data:"!=c.protocol&&c.host?c.protocol+"//"+c.host:c.href;return J[a]=c}function wa(a){"string"==typeof a&&(a=K(a));var b=a.pathname.split("/")[1];return a.origin==sa||0==a.origin.indexOf("http://localhost:")&&("c"==b||"v"==b)};function xa(a){return ba(a,function(a){var c=a.getUrl(),d;d=c;"string"==typeof d&&(d=K(d));if(wa(d)){var e=d.pathname.split("/"),f=e[1];A().assert("c"==f||"v"==f,"Unknown path prefix in url %s",d.href);var f=e[2],g="s"==f?"https://"+decodeURIComponent(e[3]):"http://"+decodeURIComponent(f);A().assert(0<g.indexOf("."),"Expected a . in origin %s",g);e.splice(1,"s"==f?3:2);e=g+e.join("/");f=(f=d.search)&&"?"!=f?(f=f.replace(ua,"").replace(/^[?&]/,""))?"?"+f:"":"";d=e+f+(d.hash||"")}else d=d.href;var k=
d,h=a.getRootNode(),l=h&&h.AMP&&h.AMP.canonicalUrl;if(!l)var m=A().assert(h.querySelector("link[rel=canonical]"),"AMP files are required to have a <link rel=canonical> tag."),l=K(m.href).href;a=String(Math.floor(1E4*a.win.Math.random()));return{url:c,sourceUrl:k,canonicalUrl:l,pageViewId:a}})};function L(a){return C(a,"viewer")};var M;function N(a,b){var c=M||(M=Object.create(null));if(b in c)a=c[b];else{var d=b;a=-1!=ya(a).indexOf(d)?!0:a.AMP_CONFIG&&a.AMP_CONFIG.hasOwnProperty(d)?Math.random()<a.AMP_CONFIG[d]:!1;a=c[b]=a}return a}
function ya(a){if(a._experimentCookie)return a._experimentCookie;var b;a:{b:{try{b=a.document.cookie;break b}catch(g){}b=void 0}if(b){b=b.split(";");for(var c=0;c<b.length;c++){var d=b[c].trim(),e=d.indexOf("=");if(-1!=e&&"AMP_EXP"==decodeURIComponent(d.substring(0,e).trim())){b=decodeURIComponent(d.substring(e+1).trim());break a}}}b=null}var f=b;return a._experimentCookie=f?f.split(/\s*,\s*/g):[]};function za(a,b,c,d,e){var f=b.dataset&&b.dataset.multiSize;if(a.crypto&&(a.crypto.subtle||a.crypto.webkitSubtle)&&!f&&wa(a.location)){var f=c,g=d.control,k=d.experiment,h;if(!(h=L(a).getParam("exp"))){var l=a.location.search;h=Object.create(null);if(l){if(0==l.indexOf("?")||0==l.indexOf("#"))l=l.substr(1);for(var l=l.split("&"),m=0;m<l.length;m++){var r=l[m],q=r.indexOf("="),x;-1!=q?(x=decodeURIComponent(r.substring(0,q)).trim(),r=decodeURIComponent(r.substring(q+1)).trim()):(x=decodeURIComponent(r).trim(),
r="");x&&(h[x]=r)}}h=h.exp}h&&(h=(h=/(^|,)(a4a:[^,]*)/.exec(h))&&h[2])&&(l=h.split(":",2)[1],g={"-1":"117152632",0:null,1:g,2:k},g.hasOwnProperty(l)?(g=g[l],a.pageExperimentBranches=a.pageExperimentBranches||{},m=!!g,k=M||(M=Object.create(null)),h=ya(a),l=-1!=h.indexOf(f)||f in k&&k[f],m=void 0!==m?m:!l,m!=l&&(m?(h.push(f),k[f]=!0):(h.splice(h.indexOf(f),1),k[f]=!1)),a.pageExperimentBranches[f]=g):B().warn("a4a-config","Unknown a4a URL parameter: ",h," expected one of -1 (manual), 0 (not in experiment), 1 (control branch), or 2 (a4a experiment branch)"));
var u={};u[c]=e;f=u;a.pageExperimentBranches=a.pageExperimentBranches||{};for(var t in f)f.hasOwnProperty(t)&&!a.pageExperimentBranches.hasOwnProperty(t)&&!a.pageExperimentBranches[t]&&N(a,t)&&(g=f[t],k=Object.keys(g),a.pageExperimentBranches[t]=g[k[Math.floor(Math.random()*k.length)]]);if(N(a,c)){var y=a.pageExperimentBranches[c];a=y;(t=b.getAttribute("data-experiment-id"))&&Aa(t?t.split(","):[])?b.setAttribute("data-experiment-id",Ba(a,t)):b.setAttribute("data-experiment-id",a);return y==e.experiment||
y==d.experiment||"117152632"==y}}return!1}function Aa(a){return a.every(function(a){return!isNaN(parseInt(a,10))})}function Ba(a,b){return a&&!isNaN(parseInt(a,10))?b?b+","+a:a:b||""};var Ca={control:"117152650",experiment:"117152651"},Da={control:"117152670",experiment:"117152671"};var Ea={control:"117152660",experiment:"117152661"},Fa={control:"117152680",experiment:"117152681"};var Ga={adsense:function(a,b){return za(a,b,"expAdsenseA4A",Ca,Da)},doubleclick:function(a,b){return!a.document.querySelector("meta[name=amp-3p-iframe-src]")&&za(a,b,"expDoubleclickA4A",Ea,Fa)}};function O(a,b,c){function d(a){c(a);e()}var e;e=function(){a&&a.removeEventListener(b,d,!1);c=d=a=null};a.addEventListener(b,d,!1);return e}function Ha(a){var b,c;if(a.complete||"complete"==a.readyState)return Promise.resolve(a);var d=new Promise(function(d,f){b="AUDIO"===a.tagName||"VIDEO"===a.tagName?O(a,"loadstart",d):O(a,"load",d);c=O(a,"error",f)}),d=d.then(function(){return a},Ia);return Ja(d,b,c)}function Ia(a){(a=a.target)&&a.src&&(a=a.src);throw A().createError("Failed to load:",a);}
function Ja(a,b,c){var d=void 0,e;e=void 0===d?a:G(self).timeoutPromise(d||0,a);b&&e.then(b,b);c&&e.then(c,c);return e};function Ka(a){a.a2alistener||(a.a2alistener=!0,N(a,"alp")&&a.addEventListener("message",La.bind(null,a)))}
function La(a,b){var c=b.data;if("string"==typeof c&&0==c.indexOf("a2a;")){var d=b.origin,e=JSON.parse(c.substr(4));b=b.source;var f=a.document.activeElement;A().assert("IFRAME"==f.tagName,"A2A request with invalid active element %s %s %s",f,e.url,d);for(var g=!1,k=b,h=f.contentWindow;k!=a.top;){if(k==h){g=!0;break}k=k.parent}A().assert(g,"A2A request from invalid source win %s %s",e.url,d);A().assert(ja(f),"A2A request from non-ad frame %s %s",e.url,d);A().assert(0==e.url.indexOf(sa),"Invalid ad A2A URL %s %s",
e.url,d);L(a).navigateTo(e.url,"ad-"+d)}};function Ma(a,b){for(var c=[],d=0;d<a.length;d++){var e=a[d];b(e,d,a)||(c.push(e),a.splice(d,1),d--)}};function Na(a,b,c){var d=a.listeningFors;!d&&c&&(d=a.listeningFors=Object.create(null));a=d||null;if(!a)return a;var e=a[b];!e&&c&&(e=a[b]=[]);return e||null}function Oa(a,b,c){var d=K(b.src).origin,e=c?b.getAttribute("data-amp-3p-sentinel"):"amp";a=Na(a,e,!0);for(var f,e=0;e<a.length;e++){var g=a[e];if(g.frame===b){f=g;break}}f||(f={frame:b,origin:d,events:Object.create(null)},a.push(f));return f.events}
function Pa(a){for(var b={sentinel:"unlisten"},c=a.length-1;0<=c;c--){var d=a[c];if(!d.frame.contentWindow){a.splice(c,1);var e=d.events,f;for(f in e)e[f].splice(0,Infinity).forEach(function(a){a(b)})}}}
function Qa(a){if(!a.listeningFors){var b=function(b){if(b.data){var d=b.data;if("string"===typeof d&&"{"===d.charAt(0))try{d=JSON.parse(d)}catch(t){B().warn("Postmessage could not be parsed. Is it in a valid JSON format?",t)}if(d.sentinel){var e;var f=d.sentinel,g=b.origin,k=b.source,h=Na(a,f);if(h){for(var l=0;l<h.length;l++){var m=h[l],r=m.frame.contentWindow;if(r)if("amp"===f){if(m.origin===g&&r==k){e=m;break}}else{var q;if(!(q=k==r))b:{for(q=k;q&&q!=q.parent;q=q.parent)if(q==r){q=!0;break b}q=
!1}if(q){e=m;break}}else setTimeout(Pa,0,h)}e=e?e.events:null}else e=h;var x=e;if(x){var u=x[d.type];if(u)for(u=u.slice(),e=0;e<u.length;e++)(0,u[e])(d,b.source,b.origin)}}}};a.addEventListener("message",b)}}function P(a,b,c,d,e){function f(b,d,f){if(e||d==a.contentWindow)"unlisten"==b.sentinel?h():c(b,d,f)}var g=a.ownerDocument.defaultView;Qa(g);d=Oa(g,a,d);var k=d[b]||(d[b]=[]),h;k.push(f);return h=function(){if(f){var a=k.indexOf(f);-1<a&&k.splice(a,1);c=k=f=null}}}
function Q(a,b,c){var d=[];"string"==typeof b&&(b=[b]);return new Promise(function(e){for(var f=0;f<b.length;f++){var g=P(a,b[f],function(a,b,c){for(var f=0;f<d.length;f++)d[f]();e({data:a,source:b,origin:c})},c);d.push(g)}})}function Ra(a,b,c,d,e){if(a.contentWindow){d.type=c;d.sentinel=e?a.getAttribute("data-amp-3p-sentinel"):"amp";var f=d;e&&(f="amp-"+JSON.stringify(d));for(a=0;a<b.length;a++)c=b[a],c.win.postMessage(f,c.origin)}}
function R(a,b,c,d){var e=this;this.a=a;this.b=c;this.m=[];this.X=P(this.a,b,function(a,b,c){e.m.some(function(a){return a.win==b})||e.m.push({win:b,origin:c});d(a,b,c)},this.b,this.b)}R.prototype.send=function(a,b){Ma(this.m,function(a){return!!a.win.parent});Ra(this.a,this.m,a,b,this.b)};R.prototype.destroy=function(){this.X();this.m.length=0};function S(a,b,c){var d=this;this.l=a;this.C=G(a.win);this.N=this.S=!1;this.i=[];this.A=0;this.U=this.M.bind(this);this.R=new R(b,"send-intersections",c||!1,function(){return Sa(d)});this.h=null}S.prototype.fire=function(){if(this.S){var a=this.l.element.getIntersectionChangeEntry();0<this.i.length&&this.i[this.i.length-1].time==a.time||(this.i.push(a),this.A||(this.M(),this.A=this.C.delay(this.U,100)))}};
function Sa(a){a.S=!0;a.l.getVsync().measure(function(){if(a.l.isInViewport())a.onViewportCallback(!0);a.fire()})}S.prototype.onViewportCallback=function(a){if(this.N!=a)if(this.N=a,this.fire(),a){var b=this.fire.bind(this),c=this.l.getViewport().onScroll(b),d=this.l.getViewport().onChanged(b);this.h=function(){c();d()}}else this.h&&(this.h(),this.h=null)};S.prototype.M=function(){this.A=0;this.i.length&&(this.R.send("intersection",{changes:this.i}),this.i.length=0)};
S.prototype.destroy=function(){this.C.cancel(this.A);this.h&&(this.h(),this.h=null);this.R.destroy()};function T(a,b,c){this.f=a;this.w=b;this.j=this.g=this.a=null;this.b=!1;this.L=c;this.D=[];this.s=L(this.f.win);this.F=null}
T.prototype.startUp=function(a,b,c){var d=this;A().assert(!this.iframe,"multiple invocations of startup without destroy!");this.a=a;this.b=b;this.a.setAttribute("scrolling","no");this.f.applyFillContent(this.a);this.g=new S(this.f,this.a,b);this.j=new R(this.a,"send-embed-state",b,function(){return U(d,d.f.isInViewport())});Q(this.a,"entity-id",this.b).then(function(a){d.w.creativeId=a.data.id});this.D.push(P(this.a,"embed-size",function(a,b,c){Ta(d,a.height,a.width,b,c)},this.b,this.b));this.f.config&&
this.f.config.renderStartImplemented?this.F=Q(this.a,["render-start","no-content"],this.b).then(function(a){var b=a.data;"render-start"==b.type?Ta(d,b.height,b.width,a.source,a.origin):V(d)}):(this.F=Q(this.a,"bootstrap-loaded",this.b),Q(this.a,"no-content",this.b).then(function(){return V(d)}));c||(this.a.style.visibility="hidden");this.D.push(this.s.onVisibilityChanged(function(){U(d,d.f.isInViewport())}));this.w.appendChild(this.a);return Ha(this.a).then(function(){return G(d.f.win).timeoutPromise(1E4,
d.F,"timeout waiting for ad response").catch(function(a){V(d);A().warn(a)}).then(function(){d.a&&(d.a.style.visibility="")})})};T.prototype.unlayoutCallback=function(){Ua(this);if(this.a){var a=this.a;a.parentElement&&a.parentElement.removeChild(a);this.a=null}};function V(a){a.L?a.L():A().info("no content callback was specified");Ua(a)}function Ua(a){a.D.forEach(function(a){return a()});a.D.length=0;a.j&&(a.j.destroy(),a.j=null);a.g&&(a.g.destroy(),a.g=null);a.L=null}
function Ta(a,b,c,d,e){var f,g;void 0!==b&&(f=Math.max(a.w.offsetHeight+b-a.a.offsetHeight,b));void 0!==c&&(g=Math.max(a.w.offsetWidth+c-a.a.offsetWidth,c));void 0===f&&void 0===g||a.f.attemptChangeSize(f,g).then(function(){Va(a,!0,g,f,d,e)},function(){return Va(a,!1,g,f,d,e)})}function Va(a,b,c,d,e,f){a.a&&Ra(a.a,[{win:e,origin:f}],b?"embed-size-changed":"embed-size-denied",{requestedWidth:c,requestedHeight:d},a.b)}
function U(a,b){a.j&&a.j.send("embed-state",{inViewport:b,pageHidden:!a.s.isVisible()})}T.prototype.viewportCallback=function(a){if(this.g)this.g.onViewportCallback(a);U(this,a)};T.prototype.onLayoutMeasure=function(){this.g&&this.g.fire()};AMP.AmpAdApiHandler=T;function Wa(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a}function Xa(a){a=parseFloat(a);return"number"===typeof a&&isFinite(a)?a:void 0};function W(a){this.u=a.document;this.J=a.document.head;this.o={};this.T={};this.W=C(a,"platform");this.o[K(a.location.href).origin]=!0;var b=this.u.createElement("link").relList;this.I=b&&b.supports?{preconnect:b.supports("preconnect"),preload:b.supports("preload")}:{};this.s=L(a);this.C=G(a)}
W.prototype.url=function(a,b){if(Ya(a)){a=K(a).origin;var c=Date.now(),d=this.o[a];if(d&&c<d)b&&(this.o[a]=c+18E4);else{this.o[a]=c+(b?18E4:1E4);var e;this.I.preconnect||(e=this.u.createElement("link"),e.setAttribute("rel","dns-prefetch"),e.setAttribute("href",a),this.J.appendChild(e));var f=this.u.createElement("link");f.setAttribute("rel","preconnect");f.setAttribute("href",a);f.setAttribute("referrerpolicy","origin");this.J.appendChild(f);this.C.delay(function(){e&&e.parentNode&&e.parentNode.removeChild(e);
f.parentNode&&f.parentNode.removeChild(f)},1E4);Za(this,a)}}};W.prototype.preload=function(a){var b=this;if(Ya(a)&&!this.T[a]){var c=this.I.preload?"preload":"prefetch";this.T[a]=!0;this.url(a,!0);this.s.whenFirstVisible().then(function(){var d=b.u.createElement("link");d.setAttribute("rel",c);d.setAttribute("href",a);d.setAttribute("referrerpolicy","origin");b.J.appendChild(d)})}};function Ya(a){return 0==a.indexOf("https:")||0==a.indexOf("http:")?!0:!1}
function Za(a,b){!a.I.preconnect&&a.W.isSafari()&&a.s.whenFirstVisible().then(function(){a.o[b]=Date.now()+18E4;var c=new XMLHttpRequest;c.open("HEAD",b+"/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?"+Math.random(),!0);c.send()})};var X={};
function $a(a,b,c){var d=Date.now(),e=b.getAttribute("width"),f=b.getAttribute("height"),g=b.getAttribute("type");A().assert(g,"Attribute type required for <amp-ad>: %s",b);for(var k={},h=0;h<b.attributes.length;h++){var l=b.attributes[h];0==l.name.indexOf("data-")&&(k[oa(l.name.substr(5))]=l.value)}if(h=b.getAttribute("json")){var m;a:{try{m=JSON.parse(h);break a}catch(ib){}m=void 0}if(void 0===m)throw A().createError("Error parsing JSON in json attribute in element %s",b);for(var r in m)k[r]=m[r]}k.width=
Xa(e);k.height=Xa(f);k.type=g;var q=xa(b),x=L(a),u=a.location.href;"about:srcdoc"==u&&(u=a.parent.location.href);e=x.getUnconfirmedReferrerUrl();f=q.canonicalUrl;g=q.pageViewId;r={href:u};m=b.tagName;var h={localDev:!1,development:w().development,filter:w().filter,minified:!0,test:!1,log:w().log,version:w().version},l=!(!a.AMP_CONFIG||!a.AMP_CONFIG.canary),t=!x.isVisible(),y;y=a;for(var ta=0,E=y;E&&E!=E.parent;E=E.parent)ta++;y=String(ta)+"-"+ab(y);k._context={referrer:e,canonicalUrl:f,pageViewId:g,
location:r,tagName:m,mode:h,canary:l,hidden:t,amp3pSentinel:y,initialIntersection:b.getIntersectionChangeEntry(),startTime:d};Object.assign(k._context,c);var va=b.getAttribute("src");va&&(k.src=va);return k}
function bb(a,b,c){b=$a(a,b,c);c=a.document.createElement("iframe");X[b.type]||(X[b.type]=0);a=cb(a);var d=K(a).hostname;a=a+"#"+JSON.stringify(b);var e=d+"_"+b.type+"_"+X[b.type]++;c.src=a;c.name=e;c.ampLocation=K(a);c.width=b.width;c.height=b.height;c.style.border="none";c.setAttribute("scrolling","no");c.onload=function(){this.readyState="complete"};c.setAttribute("data-amp-3p-sentinel",b._context.amp3pSentinel);return c}
function db(a){var b=cb(a);a=a.__AMP_TOP||a;a=D(a,a,"preconnect",void 0,W);a.preload(b,"document");var c=qa+"/1475106123549/f.js";a.preload(c,"script")}
function cb(a){var b;return aa(self,"bootstrapBaseUrl",function(){var c;c=b;var d=a.document.querySelector('meta[name="amp-3p-iframe-src"]');if(d){var e=d.getAttribute("content"),f;f=void 0===f?"source":f;A().assert(null!=e,"%s %s must be available",d,f);var g=K(e);A().assert("https:"==g.protocol||/^(\/\/)/.test(e)||"localhost"==g.hostname||pa(g.hostname),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',d,f,e);A().assert(-1==
e.indexOf("?"),"3p iframe url must not include query string %s in element %s.",e,d);f=K(e);A().assert("localhost"==f.hostname&&!c||f.origin!=K(a.location.href).origin,"3p iframe url must not be on the same origin as the current document %s (%s) in element %s. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.",e,f.origin,d);c=e+"?1475106123549"}else c=null;return c||"https://d-"+ab(a)+("."+ra+"/1475106123549/frame.html")})}
function ab(a){var b;if(a.crypto&&a.crypto.getRandomValues){var c=new Uint32Array(2);a.crypto.getRandomValues(c);b=String(c[0])+c[1]}else b=String(a.Math.random()).substr(2)+"0";return b};function eb(a){var b=a["3pla"];b||(b={},a["3pla"]=b);var c=G(a).delay(function(){G(a).cancel(c);var b=a["3pla"];b&&delete b[c]},1E3);b[c]=1};var fb={"AMP-FX-FLYING-CARPET":!0,"AMP-LIGHTBOX":!0,"AMP-STICKY-AD":!0};function Y(a){AMP.BaseElement.apply(this,arguments)}p(Y,AMP.BaseElement);n=Y.prototype;n.getPriority=function(){return 2};n.renderOutsideViewport=function(){var a;a:{a=this.element;var b=this.win["3pla"]||{},c;for(c in b)if(Object.prototype.hasOwnProperty.call(b,c)){a=!1;break a}a="prefer-viewability-over-views"==a.getAttribute("data-loading-strategy")?1.25:!0}var d=a;return!0!==d?d:AMP.BaseElement.prototype.renderOutsideViewport.call(this)};n.isLayoutSupported=function(a){return Wa(a)};
n.buildCallback=function(){var a=this;this.c=this.a=null;this.P=this.getPlaceholder();this.H=this.getFallback();this.O=!1;this.g=this.h=this.K=null;this.V=function(){return gb(a)};var b=this.element.getAttribute("type");this.config=ma[b];A().assert(this.config,'Type "'+b+'" is not supported in amp-ad');Ka(this.win);this.G=void 0;this.B=null};
n.preconnectCallback=function(a){var b=this;db(this.win);"string"==typeof this.config.prefetch?this.preconnect.preload(this.config.prefetch,"script"):this.config.prefetch&&this.config.prefetch.forEach(function(a){b.preconnect.preload(a,"script")});"string"==typeof this.config.preconnect?this.preconnect.url(this.config.preconnect,a):this.config.preconnect&&this.config.preconnect.forEach(function(c){b.preconnect.url(c,a)});var c=this.element.getAttribute("src");c&&this.preconnect.url(c)};
n.onLayoutMeasure=function(){var a=this.element,b=this.win,c=!1,d=0;do fb[a.tagName]?(d++,c=!1):"fixed"==b.getComputedStyle(a).position&&(c=!0),a=a.parentNode;while(a&&"BODY"!=a.tagName);this.O=!(!c&&1>=d);if(void 0===this.G){a:{a=this.element;do if(a=a.parentNode,fb[a.tagName]){a=a.tagName;break a}while(a&&"BODY"!=a.tagName);a=null}this.G=a}hb(this);if(this.c)this.c.onLayoutMeasure()};function hb(a){a.a&&(a.K=a.getViewport().getLayoutRect(a.a))}
n.getIntersectionElementLayoutBox=function(){if(!this.a)return AMP.BaseElement.prototype.getIntersectionElementLayoutBox.call(this);this.K||hb(this);return this.K};
n.layoutCallback=function(){var a=this;if(this.B)return this.B;A().assert(!this.O,"<amp-ad> is not allowed to be placed in elements with position:fixed: %s",this.element);eb(this.win);return this.B=na(this).then(function(b){a.a=bb(a.element.ownerDocument.defaultView,a.element,{clientId:b||null,container:a.G});a.c=new T(a,a.element,a.V);return a.c.startUp(a.a,!0)})};n.viewportCallback=function(a){this.c&&this.c.viewportCallback(a)};
function gb(a){a.a&&(a.H||a.attemptChangeHeight(0).then(function(){a.collapse()},function(){}),a.deferMutate(function(){if(a.a&&(a.H&&(a.P&&a.togglePlaceholder(!1),a.toggleFallback(!0)),-1==a.a.name.indexOf("_master"))){var b=a.a;b.parentElement&&b.parentElement.removeChild(b);a.a=null}}))}n.unlayoutCallback=function(){this.B=null;if(!this.a)return!0;this.P&&this.togglePlaceholder(!0);this.H&&this.toggleFallback(!1);this.a=null;this.c&&(this.c.unlayoutCallback(),this.c=null);return!0};function Z(a){AMP.BaseElement.apply(this,arguments)}p(Z,AMP.BaseElement);
Z.prototype.upgradeCallback=function(){var a=this,b=this.element.getAttribute("type");if(!b)return null;if(!Ga[b]||!Ga[b](this.win,this.element))return new Y(this.element);var c="amp-ad-network-"+b+"-impl";this.element.setAttribute("data-a4a-upgrade-type",c);return C(this.win,"extensions").loadElementClass(c).then(function(b){return new b(a.element)}).catch(function(c){A().error(a.element.tagName,"Unable to load ad implementation for type ",b,", falling back to 3p, error: ",c);return new Y(a.element)})};
Z.prototype.isLayoutSupported=function(a){return Wa(a)};Z.prototype.buildCallback=function(){this.element.getAttribute("type")};AMP.registerElement("amp-ad",Z);AMP.registerElement("amp-embed",Z);
})});
//# sourceMappingURL=amp-ad-0.1.js.map
